### ISSUE TITLE
Meta.fields ignored

### ISSUE THREAD

**Issue by revmischa** [marshmallow-code/apispec#100]
/lib/python3.5/site-packages/apispec/ext/marshmallow/swagger.py:450: UserWarning: Only explicitly-declared fields will be included in the Schema Object. Fields defined in Meta.fields or Meta.additional are ignored.
  "Only explicitly-declared fields will be included in the Schema Object. "

I'm not clear what I'm supposed to do to resolve this. I'm just trying to use Meta.fields with Flask-Marshmallow. Am I doomed to walk this Earth for all eternity, suffering so greatly with each passing step?

**Comment by sloria** [comment]
You will need to explicitly declare your fields to allow them to be inspected by apispec.

Do this:

```python
class PostSchema(ma.Schema):
    id = fields.Int()
    title = fields.Str()
```

Not this:

```python
class PostSchema(ma.Schema):
    class Meta:
        fields = ('id', 'title')
```

**Comment by cancan101** [comment]
To make tracking down the cause of this error easier, I would suggest logging out the class causing the issue. In my case it was a ModelSchema with a `field` containing a name that was no longer in the model.
