### ISSUE TITLE
Allow several schemas, equivalent from client POV, to resolve to the same definition

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/apispec#104]
It is possible in an application to have multiple serialization/deserialization schemas that look identical to the client but behave differently in the application.

This is the case in a MongoDB application of mine where I use an Object Document Mapper. My app code may return an object, in which case it gets marshalled using a "OO <-> json" schema. But sometimes I have to sort of skip the ODM (because I'm using the aggregation framework) and I have a "MongoDB <-> json" schema.

You could think of other examples, like multi-DB and an object that can be stored in both.

The point is all the schema attributes are the same (same fields are dump_only, etc.) but they may deserialize with different field names, for instance, or one schema may instantiate an object and the other just return plain json.

This is internal stuff, it should not be exposed to the client. So I'd like to be able to register both schemas with the same definition in the docs.

One would be the master, the one used by `schema2jsonschema` to provide a definition in the docs. The other one(s) would just refer to that definition.

I realize this might not be a common use case, but I don't think it would add too much complexity.

It could be 

1/ Implicit

```py
spec.definition('User', schema=UserObjectSchema)
spec.definition('User', schema=UserDBSchema)
```

On the second call, [schema_definition_helper](https://github.com/marshmallow-code/apispec/blob/14be6d8be8608dec4af9e215a154e521f9d8ff78/apispec/ext/marshmallow/__init__.py#L37) knows a Schema is already declared and considers the first as the master, the second as the clone.

2/ Explicit

```py
spec.definition('User', schema=UserObjectSchema)
spec.definition('User', schema=UserDBSchema, clone=True)
```

but I don't really see the need for that explicit version.

This would impact 

- [schema_definition_helper](https://github.com/marshmallow-code/apispec/blob/14be6d8be8608dec4af9e215a154e521f9d8ff78/apispec/ext/marshmallow/__init__.py#L37): check whether a shema with the same name is already registered
- [APISpec.definition](https://github.com/marshmallow-code/apispec/blob/14be6d8be8608dec4af9e215a154e521f9d8ff78/apispec/core.py#L195): add new exception allowing a definition_helper to stop the registration process so that no definition is actually added.

Any comment before I submit a PR?

**Comment by sloria** [comment]
This seems to specific a use case to justify changing apispec core. Could your application just prevent calling definition on `UserDBSchema` rather than having apispec be responsible for skipping it?

**Comment by lafrech** [comment]
Due to changes in our application, I don't have that need anymore. The theoretical point still remains.

We're using use_args / marshall_with decorators, like flask-apispec, so the Schema we specify for the [de|]serialization is the one that appears in the docs. I guess I could manage this use case in those decorators rather than in apispec core. By adding an explicit parameter to the decorator, or let it inspect some Meta in the schemas.

If the Schema appears in a Nested field, there may be a solution [passing a `ref` attribute in the parent Metadata](https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/swagger.py#L255):

```python
class Parent(Schema):
    child = field.Nested(ChildDBSchema, ref='ChildObjectSchema')
```

Totally untested and possibly wrong.

Closing this for now. Thank you for your feedback.
