### ISSUE TITLE
How to specify attributes (such as dump_only,...) on Nested fields?

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/apispec#108]
Say you have a dump_only Nested field in your model.

The model reads:

```python
class Parent(Schema):

    child = Nested(Child, dump_ony=True)
```

Assuming you added Child to the definitions, the spec then looks like

```
    "Parent": {
      "properties": {
        "child": {
          "$ref": "#/definitions/Child", 
          "readOnly": true
        },
      }, 
      "type": "object"
    }, 
```

Unfortunately, this is invalid OpenAPI spec: https://github.com/swagger-api/swagger-js/issues/402

I get this warning in ReDoc:

    Other properties are defined at the same level as $ref at "#/definitions/Parent/properties/child". They are IGNORED according to the JsonSchema spec

Has anyone here been facing this already?

Should we use the AllOf trick described [here](https://github.com/darklynx/request-baskets/issues/5)?

**Comment by lafrech** [comment]
I tried to expose the issue in the tests, but apparently, the validation in swagger-tools does not raise any error about that, so I don't have a failing test.

Here's a quick fix attempt using `allOf` to wrap all nested schemas: https://github.com/marshmallow-code/apispec/compare/dev...Nobatek:dev_nested_attributes?expand=1

**Comment by sloria** [comment]
Good catch. I think `allOf` is the correct solution, but it would be nice if it were only used when needed, i.e. only wrap in `allOf` if there are additional properties.
