### ISSUE TITLE
Remove dump parameter from `schema2parameters`

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/apispec#114]
As found by @lafrech in #112 : `schema2parameters` should only be handling client input, so `dump` should never be `True`. We should verify this and remove the `dump` parameter if possible.

**Comment by lafrech** [comment]
Copying @frol who introduced dump parameter in https://github.com/marshmallow-code/apispec/pull/38/files.

I suspect frol introduced this parameter to let his change be a non-breaking enhancement. But maybe it should have been a bugfix instead, with dump parameter implicitly False.

**Comment by frol** [comment]
Please, let me have a few hours to remember what was the point of this.

**Comment by frol** [comment]
As you can see, I haven't introduced the `dump` parameter to `fields2parameters`, I only made the code consistent in this regard.

@jmcarp has introduced the `dump` parameter to `fields2parameters` in #33 to close issue #32.

**Comment by frol** [comment]
I support the idea of dropping `dump` parameter for `fields2parameters` functions and pass `dump=False` explicitly to the downstream calls.

**Comment by lafrech** [comment]
> As you can see, I haven't introduced the dump parameter to fields2parameters, I only made the code consistent in this regard.
> 
> @jmcarp has introduced the dump parameter to fields2parameters in #33 to close issue #32.

Sorry. I read a little too fast.

In @jmcarp's flask-apispec, `fields2parameters` is called with `dump=False` as well.

> I support the idea of dropping dump parameter for fields2parameters functions and pass dump=False explicitly to the downstream calls.

We may also drop `dump` parameter for `field2parameter` (singular) and call [`field2property`](https://github.com/marshmallow-code/apispec/blob/4c1d921bcb10ac21aa1ddf3f8372cb1a7b229718/apispec/ext/marshmallow/swagger.py#L376) with `dump=False`, can't we?

**Comment by frol** [comment]
> We may also drop `dump` parameter for `field2parameter` (singular) and call field2property with `dump=False`, can't we?

I believe, we should.

**Comment by sloria** [comment]
Thanks for investigating this @lafrech and @frol.

Would either of you be willing to take a stab at a PR?
