### ISSUE TITLE
Inspect `attribute` and/or `load_from`/`dump_to` properties for marshmallow extension

### ISSUE THREAD

**Issue by mathewmarcus** [marshmallow-code/apispec#118]
If I create the following schema:

```python
class User(Schema):
    first_name = fields.String(attribute='firstName')
    last_name = fields.String(attribute='lastName')
```

and register it
```python
spec = APISpec(
    title='Users',
    version='1.0.0',
    plugins=[
        'apispec.ext.marshmallow',
    ],
)
spec.definition('User', schema=User)
```

the generated APISpec still lists the the properties as `first_name` and `last_name` instead of `firstName` and `lastName`. Similarly, the `load_from` and `dump_to` parameters are also ignored. 

Would there be interest/would it make sense to change the properties in the generated APISpec to reflect the `attribute`, `load_from`, and/or `dump_to` marshmallow field parameters?

**Comment by LeonAgmonNacht** [comment]
+1

**Comment by lafrech** [comment]
Thanks @mathewmarcus for reporting.

I think `attribute` is handled correctly. At deserialisation, first_name is the source and firstName is the target. In other words, your API exposes `first_name`, not `firstName`. `attribute` is internal implementation detail.

If you want (my guess is you do) to expose `firstName`, you may write 

    firstName = fields.String(attribute='first_name')

and your object will have a `first_name` field after deserialization.

Or use `dump_to` and `load_from`:

    first_name = fields.String(load_from='firstName', dump_to='firstName')

I think the behaviour of those parameters, although documented, can be misleading. I would like to simplify that (see https://github.com/marshmallow-code/marshmallow/issues/717).

So `attribute` works as expected AFAIU.

`dump_to` / `load_from` are supposed to be handled correctly by apispec as well. I mean they are reflected in the properties in the spec.

Closing for now as the use case you present is correct. Please reopen if you have a failing test case for `dump_to` / `load_from`, or if I misunderstood your point.
