### ISSUE TITLE
Marshmallow and webargs working together

### ISSUE THREAD

**Issue by hartror** [marshmallow-code/apispec#12]
These two libraries have a significant amount of overlap, I'd say they're almost competing if it wasn't that @sloria is responsible for both of them. 

This is a common pattern for us:

``` python
# curl -H "Content-Type: application/json" -X POST -d '{"name": "World"}' http://localhost:5000/

from flask import Flask
from marshmallow import fields, Schema
from webargs import Arg, ValidationError
from webargs.flaskparser import parser, use_args

app = Flask(__name__)
app.config.update(PROPAGATE_EXCEPTIONS=True, DEBUG=True)

@parser.location_handler('json_body')
def parse_data(request, name, arg):
    return request.json

class Hello(Schema):

    name = fields.Str(required=True)

def validate_schema(val):
    if val.errors:
        raise ValidationError('')
    return True

hello_args = {
    'hello': Arg(
        Hello().load, required=True, location='json_body', validate=validate_schema)
}

@app.route('/', methods=['POST'])
@use_args(hello_args)
def hello_world(args):
    return 'Hello {}'.format(args['hello'].data['name'])

if __name__ == '__main__':
    app.run()
```

While this isn't onerous to setup there are a couple of features that would be nice along with being an "officially blessed" pattern (and not just something in our own libraries/projects).

_A json body location_

Probably the biggest wart in our usage pattern right now. The way we're using webargs isn't ideal with the `hello` key in the above example being a little meaningless. This does suggest using webargs jointly with marshmallow in this manner might be altogether foolish?

_A Marshmallow Arg_

But continuing onwards foolishly or not. This sort of thing would improve expressiveness:

```
hello_args = {
    'hello': SmoreArg(Hello, required=True, location='json_body')
}
```

Obviously this would handle the `Hello().load` and `validate=validate_schema` sections in the example. But it could also add functionality, for example adding a request [1] to the context of the schema and formatting errors. And of course could work with the more advanced features being experimented on in smore.

---

More than happy to get my hands dirty with some of this if we can work out a nice API to be implemented.

[1] Users and database connections are attributes on our requests which would be really handy for validation.

**Comment by sloria** [comment]
Thanks @hartror for the feedback.

> These two libraries have a significant amount of overlap.

Indeed they do, though each has its own strengths (e.g. webargs knows how to parse requests; marshmallow's validation is more feature-rich). As you are suggesting, a thin integration layer could take advantage of these individual strengths.

I like the idea of being able define request arguments from a marshmallow schema, but I'm not sure that passing the schema as an `Arg` is the most intuitive interface.

If a parser knew how to construct webargs `Arg` objects from a marshmallow `Schema` and its fields, the following is theoretically possible:

``` python
class Hello(Schema):
    name = fields.Str(required=True)

@parser.use_schema_args(Hello, locations=('json', ))
def hello_world(args):
    return 'hello {}'.format(args['name'])
```

The parser could also handle returning an error response with the validation errors.

Thoughts?

**Comment by DamianHeard** [comment]
@sloria thanks for considering this request and thanks @hartror for purposing it.

@sloria I'm worried that the API you've proposed would make it difficult to use `Schemas` in conjunction with `Args`. For example, using GET params in-conjunction with a `Schema` seems like a reasonable thing to do.

I'm not sure exactly how this might work. Perhaps something along these lines?

``` python
class Hello(Schema):
    name = fields.Str(required=True)


@use_args({'order': Arg(str, location='query'))
@parser.use_schema_args(Hello, locations=('json', ))
def hello_world(args, schema_args):
    return 'hello {}'.format(args['name'])
```

I admit this feels a bit clunky but I'm more interested in advocating the use case than the syntax.

**Comment by hartror** [comment]
@sloria I really like the terseness of just inserting the schema class directly. Would something like this also be reasonable in your eyes?

``` python
class HelloMessage(object):

    def __init__(self, name):
        self.name = name

class Hello(Schema):
    name = fields.Str(required=True)

    def make_object(self, data):
        return HelloMessage(**data)

@parser.use_schema_args(Hello, locations=('json', ))
def hello_world(message):
    return 'hello {}'.format(message.name)
```

@DamianHeard I agree, personally I'd like to mix query params coming in through webargs and json bodies through marshmallow.

**Comment by sloria** [comment]
I agree that it would be useful to mix args from "vanilla"  webargs and those parsed from a marshmallow schema. This shouldn't be a problem, since webargs inserts the parsed arguments dictionaries positionally. 

I also think using marshmallow's pre- and post-processing API during parsing (as @hartror suggests) makes sense.

**Comment by hartror** [comment]
Okay sounds good! _rolls up sleeves_

First of all where should this belong? I am thinking this belongs in its own repo, something like `webargs-marshmallow`, webargs is nicely extensible so I don't think it needs to be the same library. Of course that does risk maintenance issues especially where the framework specific parsers are concerned but that is manageable with careful testing.

Implementation wise I am thinking that the most maintainable solution would be to generate an argmap that gets passed to `webargs.core.Parser.parse` that passes back a dictionary for processing by marshmallow. This could work quite well though I am concerned there could be two sources for error messages, both marshmallow and webargs. For sanity's sake it would be good for only marshmallow to be generating the messages/detail for 400 errors.

**Comment by hartror** [comment]
Okay have the [repo](https://github.com/hartror/webargs-marshmallow) up and running including a sample of the full proposed usage:

``` #!python
from flask import Flask
from webargs.flaskparser import parser
import webargs_marshmallow

schema_parser = webargs_marshmallow.SchemaParser(parser)
use_schema_args = schema_parser.use_schema_args

app = Flask(__name__)

class HelloSchema(Schema):
    name = fields.Str()

@app.route('/')
@use_schema_args(HelloSchema)
def index(hello):
    return 'Hello ' + hello['name']

if __name__ == '__main__':
    app.run()

# curl http://localhost:5000/\?name\='World'
# Hello World
```

**Comment by sloria** [comment]
Excellent. Looking good so far! Will look at it more in-depth when I get a chance.

**Comment by hartror** [comment]
I have a functionality spike in the repo now. Had a false start when I tried to use composition to build the schema parser, wrapping a provided webargs parser. The intention was for the schema parser to define the `use_schema_args` decorator, however this required access to functionality for accessing the request object and inserting the parsed object into the arguments. Most of the framework specific parsers have this functionality buried in their own decorators.

The solution I ended up using is a class mixin that overrides the parse method. It is fairly clean but it does mean that ever framework specific parser needs a class defined, something I was trying to avoid. It also means that the parser method needs to know about how to handle schemas rather than the use_args decorator. If it was the decorator handling the schema it would be trivial generate the argmap once and close over it.

Still lots to do but looking good.

**Comment by sloria** [comment]
Closing this for now. Further discussion should happen at https://github.com/hartror/webargs-marshmallow

**Comment by sloria** [comment]
Just a heads up: I am currently working on adding first-class support for marshmallow in webargs. See https://github.com/sloria/webargs/issues/61.

**Comment by DamianHeard** [comment]
Awesome @sloria. Thanks for the update!
