### ISSUE TITLE
Support Schemas for Request Body / Query Params

### ISSUE THREAD

**Issue by ewalker11** [marshmallow-code/apispec#127]
The marshmallow plugin already nicely supports schemas for response bodies, but it would be nice if it could also support schemas for request bodies/query params. I have a PR that could support this, but wanted to get feedback on the format. Here's what I was thinking:

### Body:
This would operate similarly to the existing response schema handling, where the schema would get replaced by a $ref if found in the definitions.
```yaml
post:
    description: Add your favorite pet
    parameters:
        - name: body
          schema: PetSchema
    responses:
        200:
            description: The pet that was added
            schema: PetSchema
```
Result:
```json
{
  "paths": {
    "/pet": {
      "post": {
        "description": "Add your favorite pet",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/Pet"
            }
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Pet"
            },
            "description": "The pet that was added"
          }
        }
      }
    }
  }
}
```
### Query params:
This gets a little weird, since OpenAPI doesn't really support refs for query params AFAICT. What I was thinking is that we'd iterate through all the fields in the schema and make each one a parameter.
```yaml
get:
    description: Search by pet id
    parameters:
        - name: query
          schema: PetSearchSchema
    responses:
        200:
            description: The pet that was found with the search
            schema: PetsSchema
```
Result:
```json
{
  "paths": {
    "/pet": {
      "get": {
        "description": "Search by pet id",
        "parameters": [
          {
            "type": "string",
            "name": "pet_id",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Pet"
            },
            "description": "The pet that was found with the search"
          }
        }
      }
    }
  }
}
```

**Comment by yoichi** [comment]
In your examples, "name" is specified in an element of "parameters" and it will not be carried over to result. It may cause confusion if there are query parameter named "query" or "body".
I think it is better to specify "in" in docstrings instead.

**Comment by ewalker11** [comment]
@yoichi I'm good with `in` instead of `name` 👍

**Comment by SarthakUnavailable** [comment]
How do you invoke this code though? What's the Python syntax for passing this Schema as an input? Does it have to be in the docs string? Can we not have something similar to how we pass the schema in Response?

"content": {"application/json": {"schema": "ReservationSchema"}}

**Comment by SarthakUnavailable** [comment]
Nevermind, I got it:

spec.path(
    path="/your-path",
    operations=dict(
        get=dict(
            responses={"200": {
                "description": "Documentation about the API",
                "content": {"application/json": {"schema": "YOUR_INPUT_SCHEMA"}}}}
        )
    ),
)
