### ISSUE TITLE
Combine marshmallow and tornado schema reference.

### ISSUE THREAD

**Issue by d21d3q** [marshmallow-code/apispec#132]
Using marshmallow plugin it is possible to write in docstring only class name [link](https://github.com/marshmallow-code/apispec/blob/47a3d98b67bb31f3db7bbcc3e1333f2eaf7f89fc/tests/test_ext_marshmallow.py#L73), but with tornado plugin one have to write path to definition [link](https://github.com/marshmallow-code/apispec/blob/47a3d98b67bb31f3db7bbcc3e1333f2eaf7f89fc/tests/test_ext_tornado.py#L82). 
When I am pointing to marshmallow class in tornado docstring i doesn't convert into `'$ref': '#/definitions...` in swagger json

**Comment by yoichi** [comment]
Call spec.definition() as described in
https://github.com/marshmallow-code/apispec/blob/dev/docs/using_plugins.rst

**Comment by yoichi** [comment]
You must include 'apispec.ext.marshmallow' in plugins argument of APISpec() as

```
plugins=['apispec.ext.tornado', 'apispec.ext.marshmallow']
```

to resolve marshmallow class.
