### ISSUE TITLE
Use value for "missing" in schema as "default" in Swagger spec

### ISSUE THREAD

**Issue by CausticYarn** [marshmallow-code/apispec#137]
When the schema represents a response, it makes sense that the "default" keyword for a field represents the "default" value in the Swagger spec.  However, when using the schema as a request body parser, it's actually the "missing" value that becomes the "default" for deserialization of the request body. Ideally this would be part of the Swagger specification.

This is somewhat related to #127

**Comment by sloria** [comment]
This has been fixed on `dev`.
