### ISSUE TITLE
Question: How to set 'consumes' for file upload operations

### ISSUE THREAD

**Issue by nebularazer** [marshmallow-code/apispec#149]
Hi,

i am trying to create a file upload endpoint within a flask app.

I am using a custom field to enable the fileupload in swagger-ui:

```python
@swagger.map_to_swagger_type('file', None)
class FileUploadField(fields.Raw):
    pass
```

But in order to make swagger-ui actually work i need to set:
`{'consumes': ['multipart/form-data', 'application/x-www-form-urlencoded']}`
on my post operation.

Currently i am just updating the spec manually:
```python
fix = spec.to_dict()['paths']['/projects/{id}/image']['post']
fix.update({'consumes': ['multipart/form-data', 'application/x-www-form-urlencoded']})
```

Is there a better way to do this?

**Comment by frol** [comment]
Well, `consumes` is specified on the level of method configuration, so if you use apispec to generate that part of swagger.json, you simply specify this in the docstrings:

```python
@app.route('/random')
def random_pet():
    """A cute furry animal endpoint.
    ---
    get:
        description: Get a random pet
        consumes:
            - 'multipart/form-data'
            - 'application/x-www-form-urlencoded'
        responses:
            200:
                description: A pet to be returned
                schema: PetSchema
    """
    pet = get_random_pet()
    return jsonify(PetSchema().dump(pet).data)
```

**Comment by nebularazer** [comment]
Your suggestions works fine, obviously.
I think this is more a flask apispec problem, as i am decorating my routes with flask_apispecs `marshal_with`, which seems to overwrite everything defined in the docstring.

would be nice if it would somehow just merge, what do you think?

```python
@app.route('/random')
@doc(tags=['pets'], summary='cute little animals')
@marshal_with(PetSchema, code=200, description="A pet to be returned")
def random_pet():
    """A cute furry animal endpoint.
    ---
    get:
        description: Get a random pet from docstring
        consumes:
            - 'multipart/form-data'
            - 'application/x-www-form-urlencoded'
    """
    pet = get_random_pet()
    return pet
```
resulting swagger definition
```json
"/random": {
      "get": {
        "responses": {
          "200": {
            "description": "A pet to be returned", 
            "schema": {
              "$ref": "#/definitions/PetSchema"
            }
          }, 
        }, 
        "summary": "cute little animals", 
        "tags": [
          "pets"
        ]
      }
    }
```

**Comment by frol** [comment]
*You will have a better chance to have an answer if you open the issue where it belongs (in your case, flask-apispec).*

Given that you pass `tags` and `summary` with `@doc` decorator, I guess that you should pass `consumes` that way as well.

**Comment by nebularazer** [comment]
Thank you. Putting consumes into `@doc` works.
Why did i not think of that before? :confused:

**Comment by tiangolo** [comment]
I recently had this problem. I needed a Swagger 2.0 API endpoint to receive a file upload, and Swagger UI wouldn't show the file input button until I declared it correctly.

I know this is probably not the right place to put Flask-apispec, but as this issue is one of the first hits in Google, I'll add it here, for future reference and for others that arrive here.

---

My project is based on https://github.com/tiangolo/full-stack-flask-couchdb (Flask-apispec).

I had to ["create an apispec MarshmallowPlugin"](https://apispec.readthedocs.io/en/stable/api_ext.html#apispec.ext.marshmallow.MarshmallowPlugin)

After creating the plugin, add it to the `APISpec` instance.

And then, AFTER that, create a custom `FileField`.

This is how the file where I set up Flask-apispec looks like.

`./app/api/api_v1/api_docs.py` :

```python
# Import installed packages
from apispec import APISpec
from flask_apispec import FlaskApiSpec

# Import app code
from ...main import app
from ...core import config

from apispec.ext.marshmallow import MarshmallowPlugin
from marshmallow import fields

file_plugin = MarshmallowPlugin()

security_definitions = {
    "bearer": {
        "type": "oauth2",
        "flow": "password",
        "tokenUrl": f"{config.API_V1_STR}/login/access-token",
    }
}

app.config.update(
    {
        "APISPEC_SPEC": APISpec(
            title="My awesome API",
            version="v1",
            plugins=("apispec.ext.marshmallow", file_plugin),
            securityDefinitions=security_definitions,
        ),
        "APISPEC_SWAGGER_URL": f"{config.API_V1_STR}/swagger/",
    }
)

@file_plugin.map_to_openapi_type('file', None)
class FileField(fields.Raw):
    pass

docs = FlaskApiSpec(app)

security_params = [{"bearer": []}]
```

And then, in the endpoint that I want to declare as receiving a file:

```python
# Import installed packages
import uuid
from flask import abort
from webargs import fields
from flask_apispec import doc, use_kwargs, marshal_with
from flask_jwt_extended import jwt_required, get_current_user

# Import app code
from app.main import app
from app.api.api_v1.api_docs import docs, security_params
from app.core import config
from app.utils.utils import get_message_from_image
from app.db.utils import check_if_user_is_superuser, check_if_user_is_active

from app.api.api_v1.api_docs import FileField

# For type hints
from werkzeug.datastructures import FileStorage

# Import Schemas
from app.schemas.msg import MsgSchema

@docs.register
@doc(description="Get file and to stuff", security=security_params, tags=["files"], consumes=['multipart/form-data'])
@app.route(f"{config.API_V1_STR}/upload/", methods=["POST"])
@use_kwargs({"image": FileField(required=True)}, locations=["files"])
@marshal_with(MsgSchema())
@jwt_required
def route_files_post(image: FileStorage):
    user = get_current_user()
    if not check_if_user_is_active(user):
        abort(400, "User not active")
    elif not check_if_user_is_superuser(user):
        abort(400, "User not a superuser")
    file_id = uuid.uuid4()
    file_path = f"/data/files/{file_id}"
    image.save(file_path)
    message = get_message_from_image(file_path)
    return ({"msg": message}, 200)
```

Notice that I'm using Python 3.6 type hints in the `image: FileStorage`. This is just to have code completion in the editor.

But also, notice that what it receives is not a bytes object, nor a file object, it's a [werkzeug's `FileStorage`](http://werkzeug.pocoo.org/docs/0.14/datastructures/#werkzeug.datastructures.FileStorage) object, that includes a `save` method.

That's the complete example that did the trick for me.

**Comment by katiyar11** [comment]
Hello ,
i am not expert in swagger. I am trying to make file field in flask swagger using above code but it is appearing simple text field but i need browse button to upload the file.
Please give me solution. Thank you...

My code is

from flask_restful import Resource, fields, Api, reqparse
from apispec.ext.marshmallow import MarshmallowPlugin
from flask_apispec.views import MethodResource
from flask_apispec import marshal_with, doc, use_kwargs
from marshmallow import Schema, fields
from .tokenizer import token_required
from werkzeug.datastructures import FileStorage

class UploadVideoRequestSchema(Schema):
    upload_video = fields.Raw(required=True)


class UploadVideo(MethodResource, Resource):
decorators = [token_required]
@doc(description='API to upload videos.', tags=['Video'], consumes=['multipart/form-data'])
@use_kwargs(UploadVideoRequestSchema, location=("files"))
def post(self,current_user, **kwargs):       
    return{"":kwargs[upload_video]}

output

![Screenshot (26)](https://user-images.githubusercontent.com/47425010/116226827-17f4e300-a771-11eb-827d-e25dc555e990.png)
