### ISSUE TITLE
Add chalice plugin

### ISSUE THREAD

**Issue by mathewmarcus** [marshmallow-code/apispec#157]
Would you be open to a pull request to add an extension, which would likely resemble the Flask extension, to add support for the [AWS Chalice microservice framework](https://github.com/aws/chalice)?

**Comment by sloria** [comment]
@mathewmarcus I would rather see chalice supported as a 3rd-party plugin. If you end up implementing this, go ahead and add it to the wiki: https://github.com/marshmallow-code/apispec/wiki/Ecosystem
