### ISSUE TITLE
Is there support for the rendering of custom validators?

### ISSUE THREAD

**Issue by daganharrington** [marshmallow-code/apispec#166]
New to this library and could not find in docs:

If I custom, arbitrary validator over some `field`, does this library give me hooks to include that in the spec output?

**Comment by yoichi** [comment]
What is the meaning of arbitrary validator? (maybe latter...)

* apispec does generate appropriate spec output according to the specified validators (e.g. marshmallow.validators.Range)
* There is no hook point to control apispec behavior on newly defined validators.

Regards,

**Comment by lafrech** [comment]
How would you represent that information in the spec? Is there anything in OpenAPI spec defining how to describe custom validators?

If there is no specific place for that defined by the spec, then you could add it to the description field. In this case, you might as well do it manually, I don't think apispec can be of much help.

**Comment by lafrech** [comment]
Closing this for now. Please comment/reopen if you have more info.
