### ISSUE TITLE
Marshmallow-schema'd body parameters lose 'required' and 'description' field spec

### ISSUE THREAD

**Issue by dlopuch** [marshmallow-code/apispec#168]
Consider this code:

```python
from marshmallow import Schema, fields
from apispec import APISpec

spec = APISpec(
        title='bug',
        version="0.0.1",
        plugins=(
            'apispec.ext.marshmallow',
        )
    )

class SomeBodyParam(Schema):
    name = fields.String(required=True)
    city = fields.String()
    age = fields.Integer()

spec.add_path(
    'foo/',
    {
        'post': {
            'parameters': [
                { 'name': 'some body param',
                  'in': 'body',
                  'schema': SomeBodyParam(),
                  'description': 'Description disapears and so does required',
                  'required': True
                  }
            ]
        }
    }
)

spec.to_dict()
```

The output is:

```
{'definitions': {},
 'info': {'title': 'bug', 'version': '0.0.1'},
 'parameters': {},
 'paths': OrderedDict([('foo/',
               {'post': {'parameters': [{'in': 'body',
                   'name': 'body',
                   'required': False,
                   'schema': {'properties': {'name': {'type': 'string'}, 'city': {'type': 'string'}, 'age': {'type': 'integer', 'format': 'int32'}},
                    'required': ['name'],
                    'type': 'object'}}]}})]),
 'swagger': '2.0',
 'tags': []}
```

Bug:
- The `required` field switched from True to False
- The `description` field got lost

The `name` parameter also gets renamed, but I believe this is per-spec.

I believe the cause is here: https://github.com/marshmallow-code/apispec/blob/0.27.0/apispec/ext/marshmallow/__init__.py#L148

Adding a `, required=parameter['required'] if 'required' in parameter else False` ought to fix the required bit.  Do something similar for `description`, but need to add it to [swagger.py:fields2parameters()](https://github.com/marshmallow-code/apispec/blob/0.27.0/apispec/ext/marshmallow/swagger.py#L367) signature and include it in the dict constructor in there.

That sound like a reasonable approach?

**Comment by yoichi** [comment]
@dlopuch I am grateful for the clear bug report.

I am worried that the current implementation of fields2parameters is already complicated,
but I have no idea about other ways. Could you try the fix in that way?

Regards,
