### ISSUE TITLE
Support Pyramid Framework

### ISSUE THREAD

**Issue by ergo** [marshmallow-code/apispec#214]
Hi,

I've needed to support Pyramid so I wrote extension for inspecting views in a pyramid way (not requiring global objects). I've created PR https://github.com/marshmallow-code/apispec/pull/213 with everything necessary.

**Comment by sloria** [comment]
See my comment in https://github.com/marshmallow-code/apispec/pull/213#issuecomment-390827813 . In the interest of keeping this library easy to maintain, we've stopped adding new plugins to this repo. New plugins should be maintained as separate packages. Really cool to see you've got it working!
