### ISSUE TITLE
Bottle plugin path regex bug when using argument type in the url

### ISSUE THREAD

**Issue by tshuval** [marshmallow-code/apispec#215]
When parsing the path of a bottle app in the form: `/path/to/<resourceId:int>`, the generated API path becomes `/path/to/{int}`.

reproduce:

    import re
    RE_URL = re.compile(r'<(?:[^:<>]+:)?([^<>]+)>')
    path = '/path/to/<resourceId:int>'
    RE_URL.sub(r'{\1}', path)  # --> '/path/to/{int}'

This can be fixed easily by replacing RE_URL with: `re.compile(r'<([^:]+)(?::.+)?>')`

**Comment by sloria** [comment]
Thanks for reporting @genbits . 

We would definitely review and merge a PR fixing this.

**Comment by lafrech** [comment]
Moved to https://github.com/marshmallow-code/apispec-webframeworks/.
