### ISSUE TITLE
Unable to document json fields

### ISSUE THREAD

**Issue by seeb0h** [marshmallow-code/apispec#220]
I am using apispec with marshmallow and flask.

I would like to produce an openapi json with documented fields for my json request. Like [here](https://rebilly.github.io/RebillyAPI/#/paths/~1contacts/post) (`customerID` => "The contact customer ID"):

I can't find a way to do it in the documentation and examples. Is there with a specific docstring to add in my marshmallow schemas ? Which one ? 

Thanks!

**Comment by lafrech** [comment]
If I understand correctly what you want to do, all you need is to add a `description` attribute to your field.

```python
    customer_id = String(description='The contact customer ID')
```

**Comment by seeb0h** [comment]
I cannot find this arg in [marshmallow API reference ](http://marshmallow.readthedocs.io/en/latest/api_reference.html#marshmallow.fields.Field).

But whatever, it works super fine!

Thanks for your help.

**Comment by lafrech** [comment]
This attribute is unknown to marshmallow. It is specific to apispec.

You can see it in the example on top of this page: https://apispec.readthedocs.io/en/latest/api_ext.html.

It is also documented here: https://apispec.readthedocs.io/en/latest/api_ext.html#apispec.ext.marshmallow.swagger.field2property.
