### ISSUE TITLE
Issue with tests involving response_helpers due to invalid docstrings

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/apispec#221]
I was struck by this while working on https://github.com/marshmallow-code/apispec/pull/219. But I think the test failure is not due to the change in the plugin interface.

I wonder how this feature is supposed to work. Maybe a test is missing.

The code in core.py reads:

```python
        # Process response helpers for any path operations defined.
        # Rule is that method + http status exist in both operations and helpers
        methods = set(iterkeys(path.operations)) & set(iterkeys(self._response_helpers))
        for method in methods:
            responses = path.operations[method]['responses']
            statuses = set(iterkeys(responses)) & set(iterkeys(self._response_helpers[method]))
            for status_code in statuses:
                for func in self._response_helpers[method][status_code]:
                    responses[status_code].update(
                        func(self, **kwargs)
                    )
```

I think the issue here is that it assumes `responses[status_code]` is a `dict`, which it may not be. In this example, it comes as a string `'description:some data'`.

I've pushed a branch with a [failing test](https://github.com/marshmallow-code/apispec/commit/5139b89fd4131442e89992b3d6bc1b05d6360a2a) showing this.

I'm not sure what to think about this. Perhaps the issue is in the step before, the path parser that fails to parse the YAML docstring describing the operation response.

I'm a bit confused. I don't use YAML docstrings in my code, as I use another extension to pass everything as `dict`, so this is not the part that I know best. Hence this pretty blurry question.

Filing this here for now. It kind of blocks https://github.com/marshmallow-code/apispec/pull/219 unless I either modify the test to remove offending feature, or modify the code to introduce a clumsy logic so as to avoid triggering this.

**Comment by Bangertm** [comment]
I think it's a bad test.  Add a space after the colon on [this line](https://github.com/marshmallow-code/apispec/commit/5139b89fd4131442e89992b3d6bc1b05d6360a2a#diff-2fcd5a46b0e40f462c4432126ad63de7R144) and the test will pass.  

The original test produces the following swagger with a string instead of an object following the 200 response: `"200": "description:some data"`

```json
{
    "info": {
        "version": "1.0.0",
        "title": "Swagger Petstore"
    },
    "paths": {
        "/hello": {
            "post": {
                "description": "post a greeting",
                "responses": {
                    "200": "description:some data"
                }
            },
            "x-extension": "value",
            "get": {
                "description": "get a greeting",
                "responses": {
                    "200": {
                        "description": "a pet to be returned",
                        "schema": {
                            "$ref": null
                        }
                    }
                }
            }
        }
    },
    "description": "This is a sample Petstore server.  You can find out more abo
ut Swagger at <a href=\"http://swagger.wordnik.com\">http://swagger.wordnik.com<
/a> or on irc.freenode.net, #swagger.  For this sample, you can use the api key
\"special-key\" to test the authorization filters",
    "parameters": {},
    "tags": [],
    "definitions": {},
    "swagger": "2.0"
}
```

Adding the space and your response helper produces the following swagger: 

```json
{
    "info": {
        "version": "1.0.0",
        "title": "Swagger Petstore"
    },
    "paths": {
        "/hello": {
            "post": {
                "description": "post a greeting",
                "responses": {
                    "200": {
                        "description": "lol"
                    }
                }
            },
            "x-extension": "value",
            "get": {
                "description": "get a greeting",
                "responses": {
                    "200": {
                        "description": "a pet to be returned",
                        "schema": {
                            "$ref": null
                        }
                    }
                }
            }
        }
    },
    "description": "This is a sample Petstore server.  You can find out more abo
ut Swagger at <a href=\"http://swagger.wordnik.com\">http://swagger.wordnik.com<
/a> or on irc.freenode.net, #swagger.  For this sample, you can use the api key
\"special-key\" to test the authorization filters",
    "parameters": {},
    "tags": [],
    "definitions": {},
    "swagger": "2.0"
}
```

**Comment by lafrech** [comment]
Wow, thanks. I could have been searching for a long time...

I fixed the docstrings in my rework branch (see https://github.com/marshmallow-code/apispec/pull/219) and now all tests pass.

Leaving this open until the rework PR is merged, but since it is not critical to `dev` I'd rather wait for that rather than fix in `dev` to avoid useless merge/rebase issues.

**Comment by lafrech** [comment]
I changed my mind and fixed it in `dev` branch (https://github.com/marshmallow-code/apispec/commit/82299c2b7769ba2fe51d5bb4252567159cbbbf29).

This and another issue:

```
-            operations={'get': {'parameters': [], 'responses': {'200': '..params..'}}})
+            operations={'get': {'parameters': [], 'responses': {'200': {}}}})
```

Thanks again @Bangertm for the help on this.
