### ISSUE TITLE
Marshmallow schema: Swagger-style inheritance

### ISSUE THREAD

**Issue by timakro** [marshmallow-code/apispec#226]
Currently when a marshmallow schema is inherited and registered on the specification the fields from the parent are just copied. I suggest to use `allOf` for inheritance like documented [here](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/).

**Comment by timakro** [comment]
If this doesn't get implemented you can use my plugin [apispec-swaggerinherit](https://github.com/timakro/apispec-swaggerinherit) to achieve this.

**Comment by sloria** [comment]
We don't have plans to implement this in the near future. For now, use @timakro 's plugin =)

**Comment by lafrech** [comment]
Actually, I might be tempted to add this feature in a future version.

Since @timakro's plugin is released under and incompatible license (LGPL), I'll need to start from scratch.

Thanks for sharing the plugin anyway.
