### ISSUE TITLE
Feedback on error message

### ISSUE THREAD

**Issue by loganasherjones** [marshmallow-code/apispec#239]
Hello. I had a strange bug that caused me a lot of frustration. This may be solved by the new plugin work you've been doing but here is my setup:

1. apispec - v0.38.0 (I'm doing something weird and haven't fixed it to update yet)
2. Using tornado

I was intermittently failing when calling `add_path`. The error I was getting was:

```python
APISpecError('Path template is not specified')
```

The core problem was, I had a method definition as the following:

```python
@coroutine
def post(self, *args, **kwargs):
    pass
```

The `*args` and `**kwargs` should never have been there but got populated by my editor automatically. At any rate, this came down to line 95 in `ext/tornado.py`. The type error that was generated was swallowed during the `add_path` call masking the problem a bit.

Even more curious is the fact that the failure was not consistent. It might be something wonky with my environment, but at some point, the following line was returning different output:

```python
args = list(inspect.signature(method).parameters.keys())[1:]
```

Sometimes the output of this function would be `['args', 'kwargs']` and other times it would be `[]`. I did some initial testing to try to replicate the problem in a stripped down environment, but could never reproduce. 

This turned out to be a little longer than I expected. Honestly, I'm not sure what I would expect you to do about it, except maybe point me more in the right direction with a more helpful error message?

Thanks so much for the library! It makes my life much easier, and I appreciate all the hard work. Let me know if I can help fix this problem.

**Comment by lafrech** [comment]
Indeed, I don't think we can do much about this.

The Plugin interface doesn't swallow the `TypeError` so once you update, the situation will be different and hopefully easier to debug.

Please reopen if you're still stuck, then.
