### ISSUE TITLE
Refactor: remove MarshmallowPlugin.path_helper, make YAML optional,...

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/apispec#246]
We have two types of plugins:

- web framework plugins:
  - get path from view object (with a [limitation to one path per view](https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/flask.py#L107) in Flask, see #181)
  - populate `operations` with info parsed from YAML docstrings

- marshmallow plugin
  - populate `operations` with info parsed from YAML docstrings
  - resolve marshmallow schemas in operations

Several remarks:

The path helper in marshmallow plugin is a generic path helper that expects a view function with a docstring. I'm wondering if it is of any use, since anyone using a web framework would use the dedicated path helper. Assuming a web framework is simple enough not to need more than this raw helper, then it should be `SimpleWebFrameworkPlugin.path_helper` anyway. This is not marshmallow specific at all. I'd be tempted to remove it. (It would break a few tests.) In my framework, I use `MarshmallowPlugin` but I override its path helper with a method that raises `PluginMethodNotImplementedError` to remove that feature.

The `WebFrameworkPlugin`s (flask,...) are more like `YAMLWebFrameworkPlugin`s. I'd be happy to make the YAML requirement optional. I don't use it, as I get all necessary information from the decorators I use to pass serialization and deserialization schemas. I don't think `flask-apispec` uses this either, although I didn't check. If we got rid of `MarshmallowPlugin.path_helper` already, then it's only about importing YAML stuff only in web framework plugins modules.

BTW, `load_yaml_from_docstring` and `load_operations_from_docstring` could be reworked to return `{}` rather than `None` and avoid that `or` test in each plugin: 

```python
    utils.load_operations_from_docstring(view.__doc__) or {}
```

Once we're there, we'll have `MarshmallowPlugin` with only an `operation_helper`, and a few web framework plugins with only a `path_helper`. And only one `path_helper` returning a path string should be registered at a time, as the last one speaking overrides the others. Anyway, only one should be needed.

Also the web framework path helpers deal with operations quite a lot, and perhaps this logic should be split into `path_helper` and `operation_helper`. From a quick glance, the coupling between the two seems loose. Could be a bit trickier with flask due to the `if method in rule.methods` test, which covers what looks like a twisted but legit case (method declared in the view but not in the rule).

If doing this, then the plugin registration order will matter, as those web framework operation helpers will need to be executed before marshmallow helper, for instance. But I don't think this is an issue, apart from the test it breaks. Currently the order does not matter, and there's a test to check that, but it is only because the `operations` work from the web framework plugins is done in the path helper.

Just posting here for feedback before doing anything. There's nothing really blocking in current design AFAIK, so I'm not stuck and I can totally live with it.

**Comment by sloria** [comment]
I am open to this. I agree that the `path_helper` in `MarshmallowPlugin` is a bit smelly.

> BTW, load_yaml_from_docstring and load_operations_from_docstring could be reworked to return {} rather than None and avoid that or test in each plugin:

+1.

> If doing this, then the plugin registration order will matter, as those web framework operation helpers will need to be executed before marshmallow helper, for instance. But I don't think this is an issue, apart from the test it breaks. Currently the order does not matter, and there's a test to check that, but it is only because the operations work from the web framework plugins is done in the path helper.

I haven't given much thought as to how this might break existing usages. Are you suggesting that we could keep the current behavior (order doesn't matter) if we moved some the framework plugins' path helper logic to an operation helper?

**Comment by lafrech** [comment]
> I am open to this. I agree that the path_helper in MarshmallowPlugin is a bit smelly.

Thanks. I might give it a go, then.

> Are you suggesting that we could keep the current behavior (order doesn't matter) if we moved some the framework plugins' path helper logic to an operation helper?

No, just the opposite. Moving the operations logic in a separated operation helper, assuming it is feasible, would break order independency. What I'm saying is that I don't think it is that bad that the order matters. Currently, it works just because the work on operations is done in path helpers which is kind of cheating.

It is not guaranteed to work with custom plugins, so theoretically, order matters. It just happens not to matter with the plugins we have here. What we actually test is that all path helpers are run before all operation helpers, rather than applying plugins one by one. I think we could remove `test_ext_order.py` before 1.0.0. We may also add a test to check path helpers are executed before operation helpers if that matters.

Edit: Actually, don't remove `test_ext_order.py` completely. Just modify it. See https://github.com/marshmallow-code/apispec/pull/249#issuecomment-406526834.

**Comment by sloria** [comment]
Oh ok, I see now. Fine by me.

**Comment by lafrech** [comment]
PR #249, #251, #253 cover most of this.

The part I did not address is this one:

> Also the web framework path helpers deal with operations quite a lot, and perhaps this logic should be split into path_helper and operation_helper. From a quick glance, the coupling between the two seems loose. Could be a bit trickier with flask due to the if method in rule.methods test, which covers what looks like a twisted but legit case (method declared in the view but not in the rule).

I probably won't do it. I don't even use those plugins. We don't have to do that for 1.0.

**Comment by sloria** [comment]
OK, thanks for the update @lafrech . No problem about that last issue. I've moved it to #257. I agree that we can defer it.
