### ISSUE TITLE
Field that is subclass of `fields.Int` gets `{type: string}` in the generated yaml.

### ISSUE THREAD

**Issue by TheGrandmother** [marshmallow-code/apispec#250]
Rolling Python: 3.6.5, marshmallow: 3.0.0b11 and apispec: 0.39.0

I have created a custom field like this:
```python
#custom_fields.py

class Id(fields.Integer):
    def __init__(self, **kw_args):
        if 'validate' not in kw_args or kw_args['validate'] is None:
            kw_args['validate'] = [lambda v: v > 0]
        else:
            kw_args['validate'] = kw_args['validate'].copy().append(
                lambda v: v > 0)
        super(Id, self).__init__(**kw_args)
```

And i then use it like this:
```python
class Datapoint(Schema):
    uuid = custom_fields.Id(required=True)
```

And I then add the definition and generate the specs with `to_yaml()` but then it says:
```yaml
uuid: {type: string}
```

This confuses me since the field works as expected otherwise and it will fail the validation will fail if i pass anything but an integer > 0 to the `uuid` field.

**NOTE**: I know that there is `field.UUID` but I, for some unknown reason, won't use it.

**Comment by lafrech** [comment]
You should register your custom `Field` first.

https://apispec.readthedocs.io/en/stable/api_ext.html#apispec.ext.marshmallow.MarshmallowPlugin.map_to_openapi_type

```python
@ma_plugin.map_to_openapi_type(Integer)  # will map to ('integer', 'int32')
class Id(fields.Integer):
    ...

@ma_plugin.map_to_openapi_type('integer', 'ID')
class Id(fields.Integer):
    ...
```

**Comment by TheGrandmother** [comment]
Thanks!
I had no idea :3

**Comment by TheGrandmother** [comment]
Hmmm....
this does not seem to be working actually.
Using, as per the documentation:

```python
from apispec.ext.marshmallow import MarshmallowPlugin

@MarshmallowPlugin.map_to_openapi_type('integer', 'i32')
class Id(fields.Integer):
    ...
```
I get a: `AttributeError: 'str' object has no attribute 'openapi'` exception.
 With the following partial stack trace:
```
  File "/home/grandmother/git/matomatic3/models/custom_fields.py", line 5, in <module>
    @MarshmallowPlugin.map_to_openapi_type('integer', 'i32')
  File "/home/grandmother/.local/lib/python3.6/site-packages/apispec/ext/marshmallow/__init__.py", line 146, in map_to_openapi_type
    return self.openapi.map_to_openapi_type(*args)
AttributeError: 'str' object has no attribute 'openapi'
```
