### ISSUE TITLE
Methods require docstrings

### ISSUE THREAD

**Issue by ekhaydarov** [marshmallow-code/apispec#264]
Docstrings are generally reserved for usage of the actual class/function. It does not seem like having another style of declaration taking over the docstrings pattern. Is it possible to actually complete a spec instantiation without the docstrings?

**Comment by sloria** [comment]
You are not required to use the docstring-parsing feature. apispec will ignore "normal" docstring text. You can instead build your spec within code, which is what other libraries such as flask-apispec do.
