### ISSUE TITLE
FlaskPlugin fails if FlaskInjector is injecting into a view

### ISSUE THREAD

**Issue by andho** [marshmallow-code/apispec#288]
Because FlaskInjector wraps the view function in yet another "decorator" the view passed into `add_path` is not `==` to the view retrieved from `current_app.view_functions`. The failure occurs only for views that need injection (an argument in the function signature that's not a path parameter).

If there is a workaround for this that would be great.

For a long time solution, maybe allow to add_path using rule instead of view?

**Comment by lafrech** [comment]
You may subclass `FlaskPlugin` and define a `path_helper` that accepts a `rule` parameter.

**Comment by andho** [comment]
Yeah I could do that, but I've decided not to use FlaskInjector and bootstrap the whole thing in the main app file, in kind of a convoluted way, but makes sense to me.

For anyone interested here it is.

In my view module I've defined a function like so:

```py
def add_views_to_app(app, otherDep):
    def wrapper(otherDep):
        def wrapped():
            my_view(otherDep)
        return wrapped
    my_view = app.route('/my-path', methods=['POST'])(wrapper(otherDep))
    other_view = app.route('/my-path', methods=['GET'])(otherView)
    return (my_view, other_view)
```
This function is imported in the app file and executed and then I used the return values with apispec:

```py
from mymodule import add_views_to_app
(my_view, other_view) = add_views_to_app(app, otherDep)
@app.route('/api/swagger.json')
def get_swagger():
    spec.add_path(view=my_view)
    spec.add_path(view=other_view)
    return jsonify(spec.to_dict())
```

The first part can actually be moved to the `app` file but I though the route setup being in the same file as the views will be easier to manage. The wrapper could be made more generic using injector and even the route setup (add_views_to_app) could be generalized.
