### ISSUE TITLE
Rename and release as "apispec"

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/apispec#30]
For all intents and purposes, this project's sole focus is the pluggable API doc generation proposed in #1.

I propose renaming this repo/package to `apispec`.

Note: this code still remains experimental--the new name is only to reflect the primary goals of this project.

**Comment by sloria** [comment]
@jmcarp what say you?

**Comment by jmcarp** [comment]
I like this. Sounds more professional. Just don't take smore off the PyPI until I update all the stuff that depends on it!

**Comment by sloria** [comment]
Yep. `smore` will stay on PyPIi. Next release will just be apispec 0.3.0.

**Comment by hello-josh** [comment]
Smore is such a great name but apispec is a-ok!

**Comment by sloria** [comment]
Renamed the repo and package. Just need to get the docs working once rtfd/readthedocs.org#1723 is resolved, then publish to PyPI.

**Comment by sloria** [comment]
Done!
