### ISSUE TITLE
Question about fields.Nested  and APISpec.definition() call order

### ISSUE THREAD

**Issue by alapshin** [marshmallow-code/apispec#31]
What is correct way to handle nested schemas with apispec? For example I have something like that

``` python
class BarSchema(Schema):
    baz = fields.String()


class FooSchema(Schema):
    bars = fields.Nested(BarSchema, many=True)


spec.definition('Foo', spec=FooSchema)
spec.definition('Bar', spec=BarSchema)
spec.to_dict()
```

Generated definition for Foo includes Bar as nested object instead of referencing existing definition. Changing order of schemas in spec helps

``` python
spec.definition('Bar', spec=BarSchema)
spec.definition('Foo', spec=FooSchema)
```

but what about situations with circular dependencies when FooSchema nests BarSchema and vice versa?

**Comment by itajaja** [comment]
I think PR #44 solves the problem. given the schema you provided, the output will be the following, regardless of the order:

``` json
{"Foo": {"properties": {"bars": {"items": {"$ref": "#/definitions/Bar"}, "type": "array"}}}, "Bar": {"properties": {"baz": {"type": "string"}}}}
```

(on the assumption that you meant `schema` instead of `spec` in the spec definition argument)
