### ISSUE TITLE
Consider "as_string" keyword argument for marshmallow's field.Decimal

### ISSUE THREAD

**Issue by rishi-recharge** [marshmallow-code/apispec#314]
```python
from marshmallow import fields, Schema


class Product(Schema):
    price = fields.Decimal(as_string=True)
```

Today, apispec will map the price field as a "number", which makes sense. I was wondering if apispec could consider the `as_string` keyword and map the field as a "string"?

**Comment by lafrech** [comment]
This is difficult to achieve in apispec as the mapping is between a `Field` class and a type.

I don't see a simple way to do that. It would take a new feature / a refactor.

There's been discussion in marshmallow about modifying the `Field` hierarchy to have dedicated fields by type and more general fields to get loose validation on import.

E.g. `DecimalString`, `DecimalNumber`. Then`Decimal` would use both.

This would solve this issue.

This has been proposed but to my knowledge, there's been no work on this and it won't be in marshmallow 3.

A workaround for you would be to subclass `Decimal` in a `DecimalString` field and add a custom field mapping.

**Comment by rishi-recharge** [comment]
That makes sense. Thanks for taking the time to explain it.

I'll give the suggested workaround a try. I might get lucky by the fact that custom fields get mapped to string by default.
