### ISSUE TITLE
Default values for webargs

### ISSUE THREAD

**Issue by jmcarp** [marshmallow-code/apispec#32]
Now that webargs is using marshmallow internally, we specify default argument values using the `missing` parameter:

```
arg = fields.Str(missing='foo')
```

But apispec doesn't check the `missing` key when introspective parameter defaults--it only checks `default`. To get the correct swagger default, we have to specify both parameters:

```
arg = fields.Str(missing='foo', default='foo')
```

Which isn't ideal.

Since we're using the same logic to introspect fields and schemas that are used for serialization and deserialization, one approach would be to tell `field2property` and related methods whether they're introspecting load or dump. For the specific case of parameter defaults, we'd check `default` for dump and `missing` for load.

**Comment by sloria** [comment]
I think the proposed approach--specifying whether we are dumping/loading--makes sense.

**Comment by lafrech** [comment]
I don't have the whole webargs history in mind, maybe this was correct back then, but I think current behaviour is partly wrong.

Here's what [OpenAPI docs](https://swagger.io/docs/specification/describing-parameters/) say about default parameters:

> The default value is the one that the server uses if the client does not supply the parameter value in the request.

We should use the `missing` attribute in any case. The `default` attribute of a marshmallow field is internal detail the client shouldn't care about, I suppose.

Note that if used in a REST API, the result is pretty much the same from user perspective. If using `missing`, the default value is added at deserialization, saved in DB and returned. If using `default`, the default value is not saved in DB but added at serialization and returned. To me it makes more sense to use `missing`, in this case.

Anyway, when adding a schema definition, I think we should use `missing`. I prepared a PR for that.

I was about to remove the `dump` parameter but it is also used to manage `dump_only`/`load_only` attribute so extra care should be taken about this. Postponing.

**Comment by sloria** [comment]
I hadn't thought about it that way, but you're correct--`missing` is the correct thing to check when introspecting fields.
