### ISSUE TITLE
AttributeError: 'APISpec' object has no attribute 'definition'

### ISSUE THREAD

**Issue by darwinyip** [marshmallow-code/apispec#339]
Getting AttributeError: 'APISpec' object has no attribute 'definition'.
Same for `add_path()`.

This is using:
marshmallow==2.16.3
apispec==1.0.0.b5

**Comment by lafrech** [comment]
This breaking change is documented in the changelog: https://github.com/marshmallow-code/apispec/blob/dev/CHANGELOG.rst.
