### ISSUE TITLE
Error in documentation about contributing

### ISSUE THREAD

**Issue by buxx** [marshmallow-code/apispec#344]
Hello,

In page https://apispec.readthedocs.io/en/stable/contributing.html , documentation indicate Following command:

    $ pip install -r dev-requirements.txt

But there is no more `dev-requirements.txt` file.

**Comment by sloria** [comment]
See here for the latest contributing docs: https://apispec.readthedocs.io/en/latest/contributing.html

**Comment by buxx** [comment]
Thank's !
