### ISSUE TITLE
Invalid Reference Object

### ISSUE THREAD

**Issue by Bangertm** [marshmallow-code/apispec#347]
It looks like this test:

https://github.com/marshmallow-code/apispec/blob/b4bf604b6847b87616b84aed417154a58a97a8de/tests/test_openapi.py#L616-L623

is incorrectly adding field metadata as additional properties to a reference object.  The OpenAPI v3 spec on [reference objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#reference-object) has this comment: 

> This object cannot be extended with additional properties and any properties added SHALL be ignored.

The way we are handling this for other cases where additional properties are in field metadata is with the use of `allOf` like here: https://github.com/marshmallow-code/apispec/blob/b4bf604b6847b87616b84aed417154a58a97a8de/tests/test_openapi.py#L758-L760

Prance doesn't seem to complain about extra properties in a reference object, but Swagger UI shows a warning.

**Comment by sloria** [comment]
Good catch. @Bangertm would you like to send a PR fixing this?

**Comment by Bangertm** [comment]
@sloria yes I'm got a fix along with some other refactoring of `field2property`.
