### ISSUE TITLE
Addition of views from blueprints removed ?

### ISSUE THREAD

**Issue by cutenarwhal** [marshmallow-code/apispec#353]
I notice that support for blueprints used to be possible through some additional code though not in the apispec library itself, as per https://github.com/marshmallow-code/apispec/issues/68 

Specifically this code used to work
```
from apispec import Path, utils
from apispec.ext.flask import flaskpath2swagger

def path_from_rule(spec, rule, **kwargs):
    """Path helper that allows passing a Flask url Rule object."""
    path = flaskpath2swagger(rule.rule)
    view = current_app.view_functions.get(rule.endpoint)
    # Get operations from view function docstring
    operations = utils.load_operations_from_docstring(view.__doc__)
    return Path(path=path, operations=operations)

spec.register_path_helper(path_from_rule)
```

However I think apispec itself has changed a lot since then since 'flaskpath2swagger' is no longer available. I've checked the changelog and apispec is changing quite a lot. 

Are blueprints for Flask still not considered or have I overlooked something ?

thankyou

**Comment by sloria** [comment]
As of 1.0.0b4, the Flask plugin is in a separate package, [apispec-webframeworks](https://github.com/marshmallow-code/apispec-webframeworks). `flaskpath2swagger` is now in `FlaskPlugin.flaskpath2openapi`.
