### ISSUE TITLE
RFC: Remove extracting reference from field metadata

### ISSUE THREAD

**Issue by Bangertm** [marshmallow-code/apispec#354]
Currently the Marshmallow plugin looks for 'ref' key containing a JSON reference path in field.  An example from the [tests](https://github.com/marshmallow-code/apispec/blob/29881b18e6723295870422f08c17851d49f83caf/tests/test_openapi.py#L600):
```python
class PetSchema(Schema):
    category = fields.Nested(CategorySchema, many=True, ref='#/definitions/Category')
```
This functionality seems to be redundant with the plugin's ability to store automatically store references.  It also seems like it is a more fragile way to pass reference information into the spec. 
 
This [code block](https://github.com/marshmallow-code/apispec/blob/29881b18e6723295870422f08c17851d49f83caf/apispec/ext/marshmallow/openapi.py#L343) extracts the reference and can probably be completely removed because the unbound self referencing case does not occur when a schema instance is passed to `schema2jsonschema`, which is the primary case currently (we could probably enforce that by instancing the schema within `schema2jsonschema`).

**Comment by lafrech** [comment]
I guess you can go for it.

This may also mean removing the `use_refs` parameter. Not sure.

**Comment by sloria** [comment]
Done in #363
