### ISSUE TITLE
Representing openapi's "Any Type"

### ISSUE THREAD

**Issue by kaya-zekioglu** [marshmallow-code/apispec#395]
I am trying to use `marshmallow.fields.Raw` to represent a "arbitrary json" field. Currently I do not see a way to represent a field in marshmallow that will produce a openapi property that is empty when passed through apispec.

The code in `apispec.marshmallow.openapi.OpenAPIConverter.field2type_and_format` (see https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/openapi.py#L159-L173) unconditionally sets the key `type` in the property object. However it seems that it is legal in openapi to have an empty schema (without the `type` key) which permits any type (see the "Any Type" section at the bottom of https://swagger.io/docs/specification/data-models/data-types/)

Please advise if this is possible with the current codebase or if I will need to implement a custom solution. Thanks.

**Comment by lafrech** [comment]
Thanks for reporting. Is this specific to OAS3 or does it also apply to OAS2?

What if we changed the mapping

https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/openapi.py#L52

```py
    # Assume base Field and Raw are strings
    marshmallow.fields.Field: ("string", None),
    marshmallow.fields.Raw: ("string", None),
```

into

```py
    # Base Field and Raw can be any type
    marshmallow.fields.Field: (None, None),
    marshmallow.fields.Raw: (None, None),
```

then modify `field2type_and_format` like this:

```py
    def field2type_and_format(self, field):
        type_, fmt = self.field_mapping.get(type(field), ("string", None))  # Should we default to `string` or `None`?

        ret = {}
        if type_:
            ret["type"] = type_
        if fmt:
            ret["format"] = fmt

return ret
```

?

**Comment by kaya-zekioglu** [comment]
> Thanks for reporting. Is this specific to OAS3 or does it also apply to OAS2?

I cannot find direct reference to "Any Type" in the OAS2 specification that seems equivalent to what I found in OAS3.
Despite this I believe it does apply to OAS2 because...
- In the OAS 2 docs it says that "Models are described using the Schema Object which is a subset of JSON Schema Draft 4." (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types)
- JSON Schema Draft 4 allows the "empty" schema: https://tools.ietf.org/html/draft-zyp-json-schema-04#section-3.3
- In OAS 2's Schema definition there is no mention that the "type" field is required or anything saying the the empty schema is disallowed: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject

I am not an expert in OAS or JSONSchema so maybe this reasoning is flawed, but I do believe this is possible in OAS2 as well.

> What if we changed the mapping
> 
> https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/openapi.py#L52
> 
> ```python
>     # Assume base Field and Raw are strings
>     marshmallow.fields.Field: ("string", None),
>     marshmallow.fields.Raw: ("string", None),
> ```
> 
> into
> 
> ```python
>     # Base Field and Raw can be any type
>     marshmallow.fields.Field: (None, None),
>     marshmallow.fields.Raw: (None, None),
> ```
> 
> then modify `field2type_and_format` like this:
> 
> ```python
>     def field2type_and_format(self, field):
>         type_, fmt = self.field_mapping.get(type(field), ("string", None))  # Should we default to `string` or `None`?
> 
>         ret = {}
>         if type_:
>             ret["type"] = type_
>         if fmt:
>             ret["format"] = fmt
> 
> return ret
> ```
> 
> ?

I agree that this would solve the issue that I have.

W.R.T. your comment "Should we default to `string` or `None`?": I believe that it would make the most sense to leave the default as `("string", None)` for two reasons. (1) backwards compatibility for users who expect an unknown Marshmallow field to map to `("string", None)` and (2) I think (just opinion, no evidence) that it is more common for people to implement custom fields which serialize as strings than any other data type.

Thanks you for the quick response to my issue.

**Comment by lafrech** [comment]
I agree.

Would you like to send a PR with this fix?

**Comment by kaya-zekioglu** [comment]
Certainly -- I will look into it this weekend, schedule permitting.
