### ISSUE TITLE
pyyaml dependency not working

### ISSUE THREAD

**Issue by timakro** [marshmallow-code/apispec#398]
When starting a fresh virtualenv and installing `apispec`, `pyaml` is not installed.

**Comment by lafrech** [comment]
Yes, this is now an optional dependency.

https://apispec.readthedocs.io/en/stable/changelog.html#b1-2018-07-29

> [apispec.core]: Backwards-incompatible: YAML support is optional. To install with YAML support, use pip install 'apispec[yaml]'.
