### ISSUE TITLE
APISpec.add_path overwrites paths

### ISSUE THREAD

**Issue by hello-josh** [marshmallow-code/apispec#4]
I was toying around with writing a wsgi middleware that used smore while fleshing out some ideas and noticed that `smore.apispec.APISpec.add_path` does a [full replace via `dict.update`](https://github.com/marshmallow-code/smore/blob/dev/smore/apispec/core.py#L106) when adding a new path that matches an existing path. It ends up being a last one wins situation.

What do you think about storing the Path object in `_paths` and doing a recursive merge of all of its properties when calling `add_path` and then converting to dict when `smore.apispec.APISpec.to_dict` is called?

**Comment by sloria** [comment]
> What do you think about storing the Path object in _paths and doing a recursive merge of all of its properties when calling add_path and then converting to dict when smore.apispec.APISpec.to_dict is called?

+1. I think that is a fine solution.
