### ISSUE TITLE
Adding schema with an existing name should be allowed if the schemas are identical

### ISSUE THREAD

**Issue by maxalbert** [marshmallow-code/apispec#402]
Currently adding the same (identical) schema with the same name raises a `DuplicateComponentNameError`.

Normally this makes sense, but it causes issues in combination with [apispec_oneofschema](https://github.com/timakro/apispec-oneofschema) when trying to register two `OneOfSchema` instances which multiplex the same underlying schema.

Here is a minimal example (where `SchemaA` is used in both `SchemaAorB` and `SchemaAorC`).
```python
from apispec import APISpec
from apispec_oneofschema import MarshmallowPlugin 
from marshmallow import Schema, fields
from marshmallow_oneofschema import OneOfSchema

class SchemaA(Schema):
    id = fields.Integer()

class SchemaB(Schema):
    id = fields.Integer()

class SchemaC(Schema):
    id = fields.Integer()

class SchemaAorB(OneOfSchema):
    type_schemas = {
        "ClassA": SchemaA,
        "ClassB": SchemaB,
    }

class SchemaAorC(OneOfSchema):
    type_schemas = {
        "ClassA": SchemaA,
        "ClassC": SchemaC,
    }

spec = APISpec( 
    title="MyAPI",
    version="1.0.0",
    openapi_version="3.0.2", 
    plugins=[MarshmallowPlugin()],
) 

spec.components.schema("SchemaAorB", schema=SchemaAorB)

# The following line raises DuplicateComponentNameError because
# SchemaA has already been registered as part of SchemaAorB.
spec.components.schema("SchemaAorC", schema=SchemaAorC)
```
Error:
```
~/code/apispec/apispec/core.py in schema(self, name, component, **kwargs)
    132         if name in self._schemas:
    133             raise DuplicateComponentNameError(
--> 134                 'Another schema with name "{}" is already registered.'.format(name)
    135             )
    136         component = component or {}

DuplicateComponentNameError: Another schema with name "SchemaA" is already registered.
```

It would be great if `apispec` did not raise an error in this situation, provided that the schema to be added is identical to the existing one with the same name. It should of course continue to raise an error if the schemas are actually different.

I'll submit a PR with a suggested fix soon. (I hope I'm not missing any reason why it is a bad idea to allow this.)

**Comment by Bangertm** [comment]
I think I would prefer to fix this in apispec_oneofschema. There we could check to see if the schema was already in the spec before attempting to add it.

**Comment by maxalbert** [comment]
Sure, makes sense. I'll take a look at submitting a PR there (but it will have to wait until next week). Thanks for the quick reply!

Just out of interest, what makes you prefer having this in `apispec_oneofschema` rather than `apispec` itself?

**Comment by lafrech** [comment]
I also think it should be the client's responsibility not to register twice the same component, rather than relying on apispec to ignore identical components silently.

It would be much better if you could fix this in the caller,

**Comment by Bangertm** [comment]
@maxalbert see timakro/apispec-oneofschema#3.  This is what I meant to implement before but forgot.  It's relatively straight forward to determine if one of the schemas is already in the spec and this way feels cleaner.

**Comment by maxalbert** [comment]
Great! Thanks everyone for the input, and to @Bangertm for opening the PR with the fix in `apispec_oneofschema`. 👍
