### ISSUE TITLE
Consider coercing response codes to strings

### ISSUE THREAD

**Issue by zachmullen** [marshmallow-code/apispec#422]
The OpenAPI specification [allows responses of the form 2XX, 4XX, etc](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#patterned-fields-1). Using this library, it's possible in a docstring to write something like this:

 ```yaml
responses:
    200:
        content:
            application/json:
                schema: GoodResponseSchema
    4XX:
        content:
            application/json:
                schema: RequestErrorSchema
```

This causes the following error:

```
File "/Users/zach/.pyenv/versions/3.6.5/lib/python3.6/json/encoder.py", line 353, in _iterencode_dict
    items = sorted(dct.items(), key=lambda kv: kv[0])
TypeError: '<' not supported between instances of 'str' and 'int'
```

Which happens because the `200` key is stored as an `int`, and the `4XX` key is stored as a string. A preprocessing step to make them all strings would fix that problem.

**Comment by zachmullen** [comment]
Note that just calling `to_dict` on the spec is not enough to trigger this error, this is a result of passing that return value into Flask's `jsonify`, which sorts dict keys when running in development mode.

**Comment by lafrech** [comment]
This makes total sense. In fact, in flask-rest-api, I explicitly cast to string (https://github.com/Nobatek/flask-rest-api/commit/7d688f4c788707ec0a11cb1e2b8649763c51121f).

Would you like to submit a PR for that?

**Comment by zachmullen** [comment]
Sure, can you point me to where in the code this ought to be done?

**Comment by zachmullen** [comment]
Thanks!!! 🎉 🎉
