### ISSUE TITLE
Support for Related and RelatedList

### ISSUE THREAD

**Issue by dpgaspar** [marshmallow-code/apispec#429]
Hi,

Currently I'm using apispec to create components/schemas based on Marshmallow Schemas.
Some of my Schemas are generated by marshmallow-sqlalchemy so they are ModelSchemas.
The problem arises when I have Related or RelatedList "fields" this type identified on OpenApi Schema is "string". Can you give me some advise, or improve this?

Thank you!

**Comment by dpgaspar** [comment]
Any news on this?

**Comment by andrjohn** [comment]
@dpgaspar I have a PR out that may help. At the moment, any field that is not explicitly in a field mapping in openapi.py will default to be a string. You can work around this by using an API to add your custom fields to the mapping. My PR improves the handling when the field isn't in the mapping, for example, if your RelatedList type inherits from List then it will be given the `array` type.

**Comment by dpgaspar** [comment]
oh great! Can you please make the PR reference this issue, maybe I can help further down the road.

**Comment by dpgaspar** [comment]
The problem here is that I'm using marshmallow_sqlalchemy if I add:

``` python
DEFAULT_FIELD_MAPPING = {
    ....
    marshmallow_sqlalchemy.fields.Related: ("number", None),
}
```

"solves" my problem, but this seems wrong since the extension is for marshmallow not marshmallow_sqlalchemy, does this force a new extension?

Also the `Related` type mapped to `number` is not always correct, since primary keys can be of any type.

Can you please help:
- Are there any already made extensions for this?
- A PR with a new ext for marshmallow_sqlalchemy seems ok for you?

**Comment by andrjohn** [comment]
I see that the class `RelatedList` inherits from `fields.List` and `Related` inherits from` fields.Field`. With PR #435, then these will be represented as "array" and "string" respectively. This seems correct for `RelatedList`. For Related fields, as you say, the type will vary.

You can probably work around the issue by creating your own custom field:

    @ma_plugin.map_to_openapi_type(mmfields.Number)
    class RelatedNumber(sqlfields.Related):
        pass

or after #435:

    class RelatedNumber(sqlfields.Related, mmfields.Number):
        pass

I'm not familiar with marshmallow-sqlalchemy, but it might be possible to change the `Related` class to mess with it's own type hierarchy in a way that could work.

**Comment by dpgaspar** [comment]
Nice, thank you @andrjohn, I'll explore these alternatives. I'll close this one, if I need any further help I'll open a new one
