### ISSUE TITLE
fields.Dict assumes keys are strings

### ISSUE THREAD

**Issue by AbdealiLoKo** [marshmallow-code/apispec#432]
https://github.com/marshmallow-code/apispec/blob/dev/src/apispec/ext/marshmallow/openapi.py#L422

I see here and also discussed https://github.com/marshmallow-code/apispec/issues/201 that keys are ignored.
I have a scenario where my keys are integers. I have a input which is like `{1: 2, 3: 1, 4: 3}` which takes in something like the linkages between 2 of my entities

While I could change the schema, this seems to be a limitation of the library and thought I'd mention. The `keys` can be string or integers and it would be good to allow integers

**Comment by lafrech** [comment]
I believe the idea here is that in valid JSON, keys must be strings. (https://json.org/)

**Comment by AbdealiLoKo** [comment]
Ouch, I forgot that.
```
>>> json.dumps({1:1})
'{"1": 1}'
```

I wonder which part of my stack is doing this for me ...
Closing as invalid.
