### ISSUE TITLE
MarshmallowPlugin does not follow $ref when parsing requestBody

### ISSUE THREAD

**Issue by izieg-lo3** [marshmallow-code/apispec#441]
Suppose my spec contains the following for a route:
```yaml
post:
    requestBody:
        $ref: '#/components/requestBodies/MyRequestBody'
```
The requestBody being referenced here is manually provided to `APISpec(components=...)` in the components dict (not a marshmallow schema)

Without the MarshmallowPlugin enabled, this works correctly with `apispec` and produces a valid OpenAPI doc.

After enabling the MarshmallowPlugin, I get this error:
```
File "/usr/lib/python3.6/site-packages/apispec/ext/marshmallow/__init__.py", line 206, in operation_helper
     self.resolve_schema_in_request_body(operation["requestBody"])
File "/usr/lib/python3.6/site-packages/apispec/ext/marshmallow/__init__.py", line 104, in resolve_schema_in_request_body
KeyError: 'content'
```

Is this a bug? Is there another way I can reference my requestBody?

**Comment by sloria** [comment]
Thanks for the report. This does appear to be a bug. You should be able to pass plain refs.

I won't have time to dig into this in the near future, so I'd gladly review and merge a PR.

**Comment by lafrech** [comment]
What if you pass only the ref name?

```yaml
post:
    requestBody:
        $ref: 'MyRequestBody'
```

or

```yaml
post:
    requestBody:
        $ref: MyRequestBody
```

(I don't use YAML, I'm not sure about the quotes.)

**Comment by lafrech** [comment]
@izieg-lo3 are you still stuck with this?

**Comment by lafrech** [comment]
Probably more like

```yaml
post:
    requestBody:
        'MyRequestBody'
```

or

```yaml
post:
    requestBody:
        MyRequestBody
```

actually.

**Comment by lafrech** [comment]
I'm pretty sure passing ref ID only solves this. At least with apispec 2.0.1.

Please come back to us if it doesn't.
