### ISSUE TITLE
Dev Documentations for OpenAPIConverter Initializer

### ISSUE THREAD

**Issue by billyrrr** [marshmallow-code/apispec#449]
[Initializer](https://github.com/marshmallow-code/apispec/blob/59c0361fed31bade13ce117da2d52558cc008c1b/src/apispec/ext/marshmallow/openapi.py#L113) for OpenAPIConverter does not have dev documentations ([openapi.py](https://github.com/marshmallow-code/apispec/blob/dev/src/apispec/ext/marshmallow/openapi.py)) Hence, it is difficult to figure out what conditions ```schema_name_resolvers``` have to satisfy. This results in issues such as #430. 

I was debugging a [line](https://github.com/rochacbruno/flasgger/blob/0ee67a755121000dad5b4405f2dd2bcb50c8ad51/flasgger/marshmallow_apispec.py#L15) in Flasgger, and it led me here. It initializes the OpenAPISpec in the following way, 

```Python
openapi_converter = openapi.OpenAPIConverter(
        openapi_version='2.0',
        schema_name_resolver=None,
        spec=None
    )
```

which results in an error when this [line](https://github.com/marshmallow-code/apispec/blob/59c0361fed31bade13ce117da2d52558cc008c1b/src/apispec/ext/marshmallow/openapi.py#L459) is called. It seems that ```schema_name_resolver``` should have been set to "a function returning ```None```" rather than ```None```. However, further dev documentations are required to figure out what is needed for ```schema_name_resolver```.

**Comment by lafrech** [comment]
Indeed, the docstring in `OpenAPIConverter` is incomplete.

There is a bit of documentation in `MarshmallowPlugin` docstring, though.

I think `OpenAPIConverter` is not meant to be instantiated by itself, outside of a `MarshmallowPlugin`. I can't find the source but I remember someone doing this and having issues. **Edit**: here it is https://github.com/marshmallow-code/apispec/pull/447.

**Comment by lafrech** [comment]
Obsolete. The docstring has been completed since then.
