### ISSUE TITLE
Allow to pass parameters argument to path

### ISSUE THREAD

**Issue by karec** [marshmallow-code/apispec#453]
The OpenAPI specifications allow to set parameters for a path item object https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#path-item-object to make them available for all operations.

AFAIK, [`APISpec.path()`](https://github.com/marshmallow-code/apispec/blob/dev/src/apispec/core.py#L279) method doesn't take a `parameters` argument, resulting in duplicating documentation on every operation of the path for REST APIs.

If I've not missed a something here, I would be happy to work on a PR to add that feature

EDIT: details and spelling

**Comment by lafrech** [comment]
Makes total sense to me.

PR welcome!

**Comment by karec** [comment]
On it !

**Comment by lafrech** [comment]
Closed by #455.

Thank you so much @karec for your work on this.

**Comment by lafrech** [comment]
Should `MarshmallowPlugin` get a `path_helper` to allow passing schemas as path parameters?

Just wondering out loud. I don't see a practical use case.

**Comment by karec** [comment]
Good question, I don't see a practical use case either, since we can still reference schema in our parameter object. Also, `Parameter Object` will require more than just a schema (name and in at least)
