### ISSUE TITLE
Marshmallow Pluck type not supported correctly?

### ISSUE THREAD

**Issue by stribny** [marshmallow-code/apispec#459]
Hi guys,

I was just trying to use Marshmallow 3 "nesting" via Pluck field (example taken from docs https://marshmallow.readthedocs.io/en/3.0/nesting.html) and swagger documentation rendered via `apispec` shows nested object in an array instead of flat array.

When using this example:

```
class UserSchema(Schema):
    name = fields.String()
    email = fields.Email()
    friends = fields.Pluck('self', 'name', many=True)
# ... create ``user`` ...
serialized_data = UserSchema().dump(user)
pprint(serialized_data)
# {
#     "name": "Steve",
#     "email": "steve@example.com",
#     "friends": ["Mike", "Joe"]
# }
deserialized_data = UserSchema().load(result)
pprint(deserialized_data)
# {
#     "name": "Steve",
#     "email": "steve@example.com",
#     "friends": [{"name": "Mike"}, {"name": "Joe"}]
# }
```

`apispec`-generated documentation says that ` "friends": ["Mike", "Joe"]` is in fact ` "friends": [{"name": "Mike"}, {"name": "Joe"}]`. So documentation is generated as for a normal nested object (without flattening it).

Is it just not supported yet or is there a bug?
Is there a plan to support this?

**Comment by lafrech** [comment]
Yes, this is a TODO.

You may find these discussions relevant:

- https://github.com/marshmallow-code/apispec/issues/399
- https://github.com/marshmallow-code/apispec/issues/172

We need to refactor a bit to allow supporting custom fields. Doing so would simplify supporting "core but special" fields like container fields.

**Comment by mjpieters** [comment]
The updates are not that involved, really:

- a new `pluck2properties()` would handle `isinstance(field, Pluck)`. The actual field that `Pluck` delegates to can be resolved with `field.schema.fields[field.field_name]`, after which you can pass that to `self.field2property()`.
- `nested2properties()` needs to be updated to not handle `Pluck` (if isinstance(field, Nested) and not isinstance(field, Pluck)`), or delegate to `pluck2properties()`.

I'll see about a PR for this.

**Comment by mjpieters** [comment]
In the end I just put the conversion inline in `nested2properties`, see my PR #677.
