### ISSUE TITLE
Add support for mixed types

### ISSUE THREAD

**Issue by desecho** [marshmallow-code/apispec#471]
Add support for custom Marshmallow fields which would allow mapping to swagger's Mixed types (https://swagger.io/docs/specification/data-models/data-types/#mixed-type)

**Comment by lafrech** [comment]
Related to https://github.com/marshmallow-code/apispec/pull/391?

**Comment by desecho** [comment]
Yes, searched just in issues not in pull requests.

**Comment by Bangertm** [comment]
@desecho I think that this should be possible based on #478:

```python
class MixedField(fields.Field):
    pass

def mixed_2properties(field, ret, **kwargs):
    if isinstance(field, MixedField):
        del ret['type']
        ret['oneOf'] = [{'type': 'string'}, {'type': 'integer'}]
    return ret

ma_plugin = MarshmallowPlugin()
spec = APISpec(
    title="Validation", version="0.1", openapi_version="3.0.0", plugins=(ma_plugin,)
)
ma_plugin.openapi.field_converter.add_attribute_function(mixed_2properties)

properties = ma_plugin.openapi.field_converter.field2property(MixedField())
```

Let me know if this would work for you.

**Comment by lafrech** [comment]
@desecho may we close this?

**Comment by mjpieters** [comment]
I wanted to use `metadata={"oneOf": ...}` for a `fields.String()` field with a custom validator (it can be an IPv4 or IPv6 address or a hostname), but `field_converter._VALID_PROPERTIES` does not include `oneOf`. This feels related to this specific issue, should this be reopened or made into a new issue?
