### ISSUE TITLE
Apispec registering schema property's data type as the name, potential fix

### ISSUE THREAD

**Issue by reddpy** [marshmallow-code/apispec#482]
we had similar issues to the following bug:  https://github.com/marshmallow-code/apispec/issues/200 except our issue came after the schemas were registered

With our version of Marshmallow being 3 we received errors similar to the following:
`AttributeError: 'String' object has no attribute 'data_key'`

What we had done was, we created our own subclasses defined as such:
```python
class String(fields.String):
    data_key = "string"
```

and our schema would then use these custom defined field subclasses instead of the pre-defined onces that come with Marshmallow, thus not receiving the related bug as reported by 
https://github.com/marshmallow-code/apispec/issues/200

However after registering the schemas, we would get the schemas but the names of the properties would be their type instead of the actual name:
```javascript
 {
        "properties": {
          "List": {
            "items": {
              "format": "int32", 
              "type": "integer"
            }, 
            "nullable": true, 
            "type": "array"
          }, 
          "Nested": {
            "$ref": "#/components/schemas/CardData"
          }, 
          "Number": {
            "format": "int32", 
            "type": "integer"
          }, 
          "String": {
            "format": "date-time", 
            "nullable": true, 
            "readOnly": true, 
            "type": "string"
          }
        }, 
        "type": "object"
      }
```

When digging into why the fields would show up this way, it came down to _observed_name method in the openapi.py file:
```python
    @staticmethod
    def _observed_name(field, name):
        """Adjust field name to reflect `dump_to` and `load_from` attributes.

        :param Field field: A marshmallow field.
        :param str name: Field name
        :rtype: str
        """
        if MARSHMALLOW_VERSION_INFO[0] < 3:
            # use getattr in case we're running against older versions of marshmallow.
            dump_to = getattr(field, "dump_to", None)
            load_from = getattr(field, "load_from", None)
            return dump_to or load_from or name
        return field.data_key or name
```

basically the this method is evaluating the field names as their types which was a simple fix by removing the ```field.data_key``` from the outer return statement:
```python
        if MARSHMALLOW_VERSION_INFO[0] < 3:
            # use getattr in case we're running against older versions of marshmallow.
            dump_to = getattr(field, "dump_to", None)
            load_from = getattr(field, "load_from", None)
            return dump_to or load_from or name
        return name
```
After this fix, we received the correct json data:
```javascript
{
        "properties": {
          "affiliate": {
            "format": "int32",
            "type": "integer"
          },
          "card_data": {
            "$ref": "#/components/schemas/CardData"
          },
          "created": {
            "format": "date-time",
            "nullable": true,
            "readOnly": true,
            "type": "string"
          },
          "id": {
            "format": "int32",
            "minimum": 1,
            "nullable": true,
            "type": "integer"
          }
  ......
```

I believe this fix was necessary with how the openapi.py inside apispec was registering our schemas but was unsure of the removal of the field.data_key from the _observed_name method being a valid workaround for the json schema property name issue.

**Comment by lafrech** [comment]
I'm sorry, I don't get the point.

Apparently, you set `data_key = "string"` at some point, which I don't understand. This led to issues in the generated spec. You could fix the issue by changing the code but this change actually breaks a feature and you probably shouldn't be doing this in the first place.

apispec intends to use data_key if not None as the field name in the spec.

Closing for now. Feel free to comment if this is still an issue with latest marshmallow and apispec versions.
