### ISSUE TITLE
Drop marshmallow 3.0.0 RC releases compatibility

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/apispec#485]
https://github.com/marshmallow-code/apispec/blob/78b14803dc966a2c41413f7e08aadcecc193b0b3/src/apispec/ext/marshmallow/openapi.py#L432-L442

MA3 stable is out, we don't need to support older RC versions.

We could rework this in next release.

Leaving it for now to avoid unnecessary conflicts with #478.

**Comment by sloria** [comment]
Good idea; should do this on all the marshmallow libs, probably.
