### ISSUE TITLE
Allow `many=True` schemas in `requestBody`

### ISSUE THREAD

**Issue by Ianleeclark** [marshmallow-code/apispec#494]
Hi there,

I recently came across what I believe to be is a bug. If you have a schema with the `many` flag set to `True`, the schema in the `requestBody` will not be of type `array`. 

I have traced this to the following line of code: https://github.com/marshmallow-code/apispec/blob/32b6c322ff17cd4e5ddbc89968c7014ff2f7808d/src/apispec/ext/marshmallow/openapi.py#L288

Is this meant to be supported in the OAS 3.0 spec? When I looked over it, I couldn't find anything outright stating this isn't possible--specifically referring to https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject

**Comment by Bangertm** [comment]
Apispec does not take the `many` flag into account when converting marshmallow schemas to json schemas. The reason is that generally apispec prefers to use reference objects to defining schemas inline. If a schema is used both with `many` set and not set it is convenient to refer to the same schema for both cases. 

In the case of expecting an `array` in the `requestBody` change the `schema` item in the content type from: 
```yaml
schema: MySchema
```
to
```yaml
schema:
  type: array
  items: MySchema
```
That should produce the appropriate spec.

**Comment by Ianleeclark** [comment]
@Bangertm Thanks for the reply! However, I think we may have talked past each other.

> The reason is that generally apispec prefers to use reference objects to defining schemas inline.

It should be possible to use an array reference for the `requestBody`, a.k.a.,

```python
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/TestSchema"
                }
              }
            }
          }
```
> If a schema is used both with many set and not set it is convenient to refer to the same schema for both cases.

See the above example. Any change made to respect `many` wouldn't require redefinition of the schema. The only change I want here is to make `requestBody` show if a schema is an array, not to fundamentally change any schemas.

Does that better outline the problem that I'm facing?

**Comment by Bangertm** [comment]
I'm not exactly sure what the question is. If input a `requestBody` such as: 

```python
{
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "array",
                    "items": "TestSchema"
                }
            }
        }
    }
}
```
`TestSchema` will be added to the spec and the output will be exactly as in your example.

Input that will _not_ produce output equivalent to the above is:
```python
{
    "requestBody": {
        "content": {
            "application/json": {
                "schema": TestSchema(many=True)
            }
        }
    }
}
```

In this case `TestSchema` will still be added to the spec but it will be referenced as a singleton in the `requestBody`: 

```python
{
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "$ref": "#/components/schemas/TestSchema"
                }
            }
        }
    }
}
```

If that doesn't help perhaps an executable example would help me understand the issue.

**Comment by Ianleeclark** [comment]
> Input that will not produce output equivalent to the above is:

This is the part that I'm interested in. Why won't a `many=True` produce an array, but instead a singleton? The `many=True` is not some fundamental truth of the `TestSchema`, but instead a modifier.

It seems like a bug to me because you're either registering that schema as inherently being an array, or you're discarding valuable information regarding that endpoint. Am I missing a third option?

**Comment by odiroot** [comment]
As I'm also hit by this bug I'm gonna try to explain the use case.

Imagine your API accepts a POST/PUT/PATCH with a list of objects.

```json
[
    {
        "id": 1,
        "foo": "bar",
        "flag": true
    },
    {
        "id": 2,
        "foo": "qux",
        "flag": true
    },
    {
        "id": 3,
        "foo": "ham",
        "flag": false
    }
]
```

with an obvious schema:

```python
class MyEntity(Schema):
    id = fields.Integer()
    foo = fields.String()
    flag = fields.Boolean()
```

So the request body is literally `MyEntity(many=True)`.

Now this line: https://github.com/marshmallow-code/apispec/blob/32b6c322ff17cd4e5ddbc89968c7014ff2f7808d/src/apispec/ext/marshmallow/openapi.py#L288
Always assumes the child object is always of `object` type. This being an array is never taken into account, seemingly.

**Comment by Bangertm** [comment]
It turns out that contrary to my comment above, apispec _does_ take `many=True` into account for schemas in the request and response body.  

For example: 

```python
class MyEntity(Schema):
    id = fields.Integer()
    foo = fields.String()
    flag = fields.Boolean()

spec.path(
    path="/pet",
    operations={
        "post": {
            "requestBody": {
                "description": "a pet schema",
                "required": True,
                "content": {"application/json": {"schema": MyEntity(many=True)}},
            },
            "responses": {
                200: {
                    "description": "success",
                    "content": {"application/json": {"schema": MyEntity(many=True)}},
                }
            }
        }
    },
)
```
Will produce the following: 

```yaml
paths:
  /pet:
    post:
      requestBody:
        description: a pet schema
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/MyEntity'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MyEntity'
info:
  title: Validation
  version: '0.1'
openapi: 3.0.0
components:
  schemas:
    MyEntity:
      type: object
      properties:
        foo:
          type: string
        id:
          type: integer
          format: int32
        flag:
          type: boolean
```

The reference objects for in the request and response are both in arrays and `MyEntity` is added to the spec in singleton form. Can you be more specific about how you are hitting the issue?

**Comment by lafrech** [comment]
A reproducible example would help clarifying the issue.

**Comment by lafrech** [comment]
Closing this due to lack of feedback. Feel free to comment and we'll reopen.
