### ISSUE TITLE
No module named 'apispec'

### ISSUE THREAD

**Issue by Bernardoow** [marshmallow-code/apispec#502]
I'm using pipenv and used pipenv install apispec="==2.0.2". So I call the method in my file "from apispec import APISpec" and the got the error :

from apispec import APISpec
E   ModuleNotFoundError: No module named 'apispec'

**Comment by sloria** [comment]
This is difficult to diagnose without more details. What version of Python are you using? Do you have a file called `apispec.py` that might be shadowing the import?

**Comment by Bernardoow** [comment]
Sorry. Some thing happend with my pipenv. So I restarted my pc and then come worked normaly.

Sorry again.
