### ISSUE TITLE
`type: object` not added to a Field leads to weirdness

### ISSUE THREAD

**Issue by flaker** [marshmallow-code/apispec#505]
Hi,
I am using apispec with Marshmallow. I've noticed that while trying e.g. the swagger editor (https://editor.swagger.io/) one parameter is not present even when it's required. My field is declared as:

`snapshot = ma.fields.Field(required=True, description='The state of the entity.')`

and the json generated looks like:

```
        "snapshot": {
          "description": "The state of the entity."
        }, 
```

If I add `"type": "object"`, the parameter shows up. This field can receive in practice anything that can be json serializable (eventually). But since we don't know  what is it going to be, we chose "Field". Should we be using something else?

Thanks.

**Comment by Bangertm** [comment]
Hi, Can you provide an executable example to illustrate the problem.

**Comment by lafrech** [comment]
Related to #395 / #495.

From the conversations there, current behaviour should be correct.

**Comment by lafrech** [comment]
Closing this due to lack of feedback. Feel free to comment and we'll reopen.
