### ISSUE TITLE
apispec-3.0.0 incompatible with apache-airflow

### ISSUE THREAD

**Issue by benbendemo** [marshmallow-code/apispec#507]
Hi, i need to report one issue, when my Python version is:2.7.5, when i use "pip install apispec", it will automatically install the latest version apispec-3.0.0.

Afterwards, when i execute "airflow webserver" command, it just throws "SyntaxError: invalid syntax" error like below picture.

<img width="694" alt="image" src="https://user-images.githubusercontent.com/4705587/66110056-8951cb80-e5f8-11e9-8855-3130d056eb4b.png">

I checked "core.py" file in apispec package, on line 224, there is a "*" parameter in path function, guess that's the reason why "airflow webserver" could'n work.

**Comment by lafrech** [comment]
Support for Python 2 was dropped in apispec 3.0.

https://apispec.readthedocs.io/en/latest/changelog.html#id1

Changelog
3.0.0 (2019-09-17)

Drop support for Python 2 (#491).

**Comment by benbendemo** [comment]
Then i upgrade Python version from 2.7.5. to 2.7.15, uninstall apispec and then reinstall apispec, i got apispec-2.0.2 version.I was confused why i didn't got the latest version?

When execute "airflow webserver",i got this below, could you give some help?
 
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/4705587/66110781-0d588300-e5fa-11e9-8c73-b282f83d2e2c.png">

**Comment by lafrech** [comment]
marshmallow-sqlalchemy also dropped Python 2.

Use a new virtualenv and hopefully, pip will not pull in versions that drop Python 2 support.

If not, pin your dependencies to versions before the PY2 drop.

Also, Python 2 is reaching end of life, so you should consider porting your code to Python 3, obviously.
