### ISSUE TITLE
Should I handle basePath removal a little better?

### ISSUE THREAD

**Issue by hello-josh** [marshmallow-code/apispec#51]
#50 works the way I had hoped but I felt like it cluttered up `APISpec.add_path` with a bunch of conditional logic. What do you think about using a non-data descriptor for `APISpec._paths` and a `dict` subclass that strips `basePath` from any keys set?

https://github.com/marshmallow-code/apispec/compare/dev...Trii:path-as-descriptor

**Comment by sloria** [comment]
I'm leaning towards "KISS" on this issue, and adding two custom data structures feels a bit over-engineered for this simple use case. Let's keep it as is for now. Thanks for putting so much thought into this.

**Comment by hello-josh** [comment]
Sounds good to me too. I'll keep the branch around in case it warrants it at a later date.
