### ISSUE TITLE
Tag objects should be unique ?

### ISSUE THREAD

**Issue by kwinstonix** [marshmallow-code/apispec#523]
I used `APISpec.tag()` for each OAS Operation object, so the `swagger.yaml` contains many  duplicate tag objects, so I think it should be better if we remove duplicate tag objects here.

https://github.com/marshmallow-code/apispec/blob/1f386092f7b8693d635a707e94f81420a2d48175/src/apispec/core.py#L212

```
_tags = [{'name': "tag name" , 'description': 'desc'}]
```

**Comment by lafrech** [comment]
I'd rather deduplicate in `tag` method.

https://github.com/marshmallow-code/apispec/blob/1f386092f7b8693d635a707e94f81420a2d48175/src/apispec/core.py#L230-L236

But how to deal with several tag definitions with different attributes?

We should instead only raise a warning if multiple tags with the same id are defined.

How come you register the same tag multiple times? Can't you address this in the first place?

**Comment by kwinstonix** [comment]
Thanks for your reply.  Yes,  you are right,  should deduplicate in `tag` method, I created a subclass of `APISpec` and overwrite `tag` method. 

I can address this problem, because I register each operation with same tag, like these three API, tag name is `user`.   

```
GET /users
GET /users/1
POST /users
```

So spec file result is like this.  There is no problem  to render this spec file with UI tools, it works good. I just wonder whether tags should be unique by name  🤔

```
tags:
- {name: user}
- {name: user}
- {name: user}
```

**Comment by lafrech** [comment]
https://swagger.io/specification/#oasObject

> Each tag name in the list MUST be unique.

Your spec is invalid. it is not _that_ bad since it displays correctly.

I don't think apispec should address this, except maybe by issuing a warning.

**Comment by kwinstonix** [comment]
emm, I have read OAS spec,  My spec is invalid indeed, `redoc` can render it,  and I could fix it. I just open this issue to discuss this situation . issuing a warning maybe a better choice？

thank you  again, we should close this issue now
