### ISSUE TITLE
Ability to access APISpec.components in plugin init_spec method

### ISSUE THREAD

**Issue by Colin-b** [marshmallow-code/apispec#538]
Is there a specific reason why components is initialized after plugins init_spec methods are called?

If not, then I am willing to open a PR to solve this issue.

**Comment by lafrech** [comment]
Plugins must be `init_spec`ed  before they are used in `Components` but the don't *have* to be at `Components` init time so we could initialize `Components` first.

I'm open to a PR.

I'd be curious about your use case, though. can you please elaborate? If someone ever needs to reverse this, I'd like to know why we're doing it.

**Comment by Colin-b** [comment]
My plugin needs to register components that are shared across various endpoints (because they are related to Exception handling).

I cannot register the same component more than once (a DuplicateComponentNameError is raised, and it make sense) so I cannot do it every time a endpoint using this component is registered. 

I could but it would require my code to rely on a private attribute from apispec.Components, `_schemas` and I would like to avoid that as you can imagine ;-)

In order to do it automatically without requiring any action from the user (manually registering each component once), I would like to register components inside the plugin init_spec.

The user of this plugin should not have to call anything to have those components available :)

If you say that this is still a valid use case I will gladly submit a PR

**Comment by lafrech** [comment]
Makes sense. Let's move plugins init_spec to the end of APISpec init.

PR welcome.

If you can think of a minimal test case to use as a non-reg test, that's great.

Don't forget to add yourself to AUTHORS file.

Thanks.
