### ISSUE TITLE
Bad serialization with load_operations_from_docstring

### ISSUE THREAD

**Issue by martinlatrille** [marshmallow-code/apispec#54]
Hello,

I noticed a problem while using the `apispec.utils.load_operations_from_docstring` method.

While trying to parse the following docstring:

``` python
"""
Fetch multiple stuff

---
  get:
    description: Returns stuff
      responses:
        200:
          description: A list of stuff.
            produces: [ application/json ]
            schema:
              type: array
              items:
                $ref: "#/definitions/Stuff"
"""
```

Using this code:

``` python
spec.add_path(path=Path(path="/api/stuff", operations=load_operations_from_docstring(method.__doc__)))
```

The `200` response was serialized as an `int`, and not as a `string`. As a result, the JSON was not valid.
I did a little workaround, a path_helper you can find below. Maybe this should be included as a default path_helper, or the behavior should be fixed somehow.

``` python
def yaml_serializer(apispec, **kwargs):
    def replace_nums(d):
        for k, v in d.items():
            if isinstance(k, int):
                d[str(k)] = v
                del d[k]
            if isinstance(v, dict):
                replace_nums(v)

    replace_nums(kwargs['path'])
    return kwargs['path']

spec.register_path_helper(yaml_serializer)
```

(Also, writing 'items: StuffSchema' in the docstring didnt work as expected, so I had to add the "$ref" line manually.)

I'm not at ease enough with the project to make a PR yet, but I thought I should tell you guys !

EDIT: along with the fix for the bad-formatted integers as key, the fix for the bad-formatted "schema" value

``` python
def yaml_serializer(apispec, **kwargs):
    def replace_nums(d):
        for k, v in d.items():
            if isinstance(k, int):
                d[str(k)] = v
                del d[k]
            if isinstance(v, dict):
                replace_nums(v)

    def add_schema_ref(d):
        for k, v in d.items():
            if k == "schema":
                if not isinstance(v, dict):
                    d[k] = {'$ref': '#/definitions/' + v.replace('Schema', '')}
                elif v.get('items', False) and not isinstance(v, dict):
                    schema = v['items']
                    v['items'] = {'$ref': '#/definitions/' + schema.replace('Schema', '')}
            elif isinstance(v, dict):
                add_schema_ref(v)

    replace_nums(kwargs['path'])
    add_schema_ref(kwargs['path'])
    return kwargs['path']

spec.register_path_helper(yaml_serializer)
```

**Comment by hello-josh** [comment]
I noticed something similar a couple of weeks ago so I ended up listing the status codes in single quotes in my docstrings.

**Comment by martinlatrille** [comment]
Well, you can use this path_helper now :wink:

**Comment by martinlatrille** [comment]
Update: sometimes, I'm a retard. "json.dumps()" totally fix the int-key serialization issue.
Though, the fix for the schemas' ref is useful !
