### ISSUE TITLE
question: array schema reference

### ISSUE THREAD

**Issue by oxlade39** [marshmallow-code/apispec#547]
When using the docstring to reference a `schema` what is the correct approach when the route returns an array of said schema:

```python
def myroute():
    """
    Return many
    ---
    get:
        produces:
        - application/json
        responses:
            '200':
                content:
                    application/json:
                        type: array
                        schema: ModelSchema
    """
    return jsonify(ModelSchema().dump(selected_models, many=True))
```

**Comment by oxlade39** [comment]
answer is:
```yml
responses:
            '200':
                description: The SignalError
                content:
                    application/json:
                        schema:
                            type: array
                            items: QuantModelSchema
```
would be nice if there was an example of this somewhere.

**Comment by Bangertm** [comment]
There is some documentation of that [here](https://apispec.readthedocs.io/en/latest/api_ext.html#apispec.ext.marshmallow.schema_resolver.SchemaResolver.resolve_schema_dict). Possibly a little deep in the documentation though... Please feel free to propose a pr for where you would have expected to see it.
