### ISSUE TITLE
Is there a way to programmatically upload spec output to swaggerhub?

### ISSUE THREAD

**Issue by efreethy** [marshmallow-code/apispec#551]
After generating specs it would be nice to push this to swagger hub using an API key - but its not clear that there is support anywhere out there. I can't find any tools that do just this.

**Comment by lafrech** [comment]
I don't know about swagerhub. There is nothing related to it in apispec. It belongs to user code. Or perhaps to a dedicated lib.

Maybe another apispec user knows about it and will be able to help you.

**Comment by lafrech** [comment]
Closing as this is out of scope.
