### ISSUE TITLE
`load_from` should be used for request body

### ISSUE THREAD

**Issue by emyller** [marshmallow-code/apispec#567]
Currently `dump_to` is prioritized regardless of the field being used for a request (loading) or a response (dumping):

https://github.com/marshmallow-code/apispec/blob/aef2b1f7c5c86c252a2e1c45d28d2dfd951aafaa/src/apispec/ext/marshmallow/openapi.py#L75

This leads to incorrect spec when those values differ. The logic was introduced in #183.

**Comment by diegoprd** [comment]
Not sure to understand the issue... :/ sorry

**Comment by lafrech** [comment]
I don't think the logic was better before #183.

This is a known but not really documented edge issue when using marshmallow 2 with dump_to != load_from.

I might not be very helpful but my suggestion would be not to do it. Marshmallow 2 is reaching EOL (in 3 months) and in marshmallow 3, there is only one parameter: `data_key`.

**Comment by emyller** [comment]
@lafrech That sounds fair enough. Also, issue has a somewhat easy workaround:

```python
class MySchema(Schema):

    name = fields.String(
        load_from='requestName',
        # dump_to='responseName',
    )

    @post_dump
    def fix_name(self, data):
        data['responseName'] = data.pop('name')
        return data
```

**Comment by lafrech** [comment]
I don't think this will work when documenting the response.

The way to go is to use 2 schemas. You'll have to when moving to marshmallow 3, I'm afraid.

**Comment by lafrech** [comment]
Obsolete. Marshmallow 2 was dropped.
