### ISSUE TITLE
fields.Method doesn't generated into swagger doc

### ISSUE THREAD

**Issue by azzamsa** [marshmallow-code/apispec#575]
MWE:

```python
...
class PetSchema(ma.Schema):
    class Meta:
        strict = True
        ordered = True

    id = ma.fields.Int(dump_only=True)
    name = ma.fields.String()
    foo = ma.fields.Method()


blp = Blueprint("pets", "pets", url_prefix="/pets", description="Operations on pets")

@blp.route("/")
class Pets(MethodView):
    @blp.response(PetSchema(many=True))
    def get(self):
        """List pets"""
        # TODO
        # return Pet.select()


...
```
![image](https://user-images.githubusercontent.com/17734314/85666749-053ff680-b6e7-11ea-9528-61b64265b4ad.png)

![image](https://user-images.githubusercontent.com/17734314/85666731-ff4a1580-b6e6-11ea-809e-a8968a4e848e.png)

**Comment by lafrech** [comment]
Transferring to apispec.

What would you expect?

There is no way to tell what the `Method` field does, so it can't be automatically documented.

(When investigating this kind of issues, quoting a part of the generated file is better than a screenshot, as OpenAPI UIs may hide things, like incomplete or invalid descriptions.)

**Comment by azzamsa** [comment]
> There is no way to tell what the Method field does, so it can't be automatically documented.

Thanks for the clue. I need all the arguments and responds to be well-documented so I think I need to specify id to `field.Int` and parse the value outside the schema.

Thank you for apispec.

**Comment by kettenbach-it** [comment]
I think this is possible:

`foo = ma.fields.Method("method.....", type="integer")`

But you are limited to a couple of simple datatypes you can find here:
https://swagger.io/docs/specification/data-models/data-types/

For more complex datatypes, you could either try to use this:
https://github.com/marshmallow-code/marshmallow/issues/1638#issuecomment-661981734
which I didn't get to work (in a project with flask-smorest)

or you have to wait until someone implements this:

https://github.com/marshmallow-code/marshmallow/issues/513

**Comment by azzamsa** [comment]
> foo = ma.fields.Method("method.....", type="integer")

voilà, after adding `type="string"`, now the attribute appears in the scema.

Thanks @kettenbach-it
