### ISSUE TITLE
Writing plugins documentation is out of sync

### ISSUE THREAD

**Issue by jimmy-lt** [marshmallow-code/apispec#576]
The first piece of code within the [Writing Plugins documentation](https://apispec.readthedocs.io/en/latest/writing_plugins.html) is the following:

```py
from apispec import Path, BasePlugin
from apispec.utils import load_operations_from_docstring


class MyPlugin(BasePlugin):
    def path_helper(self, path, func, **kwargs):
        """Path helper that parses docstrings for operations. Adds a
        ``func`` parameter to `apispec.APISpec.path`.
        """
        operations = load_operations_from_docstring(func.__doc__)
        return Path(path=path, operations=operations)
```

However, the name `Path` does not exists in apispec's [latest version](https://github.com/marshmallow-code/apispec/blob/3.3.1/src/apispec/__init__.py). The same is for `load_operations_from_docstring` which is not found into `apispec.utils` but better in `apispec.yaml_utils`.

**Comment by lafrech** [comment]
Fixed. Thanks for reporting.
