### ISSUE TITLE
spec.tag generates duplicate JSON entries leading to invalid JSON

### ISSUE THREAD

**Issue by mattheiter** [marshmallow-code/apispec#588]
When I call:

`spec.tag({'name': 'test', 'description': 'test'})`

This generates the tag multiple times, which is invalid:

```

 "tags": [
    {
      "description": "test",
      "name": "test"
    },
    {
      "description": "test",
      "name": "test"
    }
  ]
```

**Comment by Bangertm** [comment]
Can you include a executable example illustrating the issue. When running this test as an example:  

https://github.com/marshmallow-code/apispec/blob/57a32f8810982c62233e6721556905dfe9a08065/tests/test_core.py#L124-L127

there is only a single entry in `tags`.

**Comment by lafrech** [comment]
Are you calling `spec.tag` multiple times?

If so, I'd say this is user code issue. apispec is not responsible for removing redundant tags.

**Comment by mattheiter** [comment]
You are right. I just checked the Flask documentation and it is possible that code is executed multiple times [if it isn't run with the flask call](https://flask.palletsprojects.com/en/1.1.x/server/). After moving the tag definitions from the app.py module to an individual module, containing only the spec definition, the problem disappeared.

Thank you for the quick responses 👍
