### ISSUE TITLE
KeyError, missing SchemaKey for Nested schemas

### ISSUE THREAD

**Issue by 2nv2u** [marshmallow-code/apispec#594]
Whenever the `SchemaKey` is missing from the `self.refs` it's never added:
https://github.com/marshmallow-code/apispec/blob/f075149bbd1238c1e9e17f5281d18bc0954739cd/src/apispec/ext/marshmallow/openapi.py#L92
Making the `get_ref_dict` method call fail:
https://github.com/marshmallow-code/apispec/blob/f075149bbd1238c1e9e17f5281d18bc0954739cd/src/apispec/ext/marshmallow/openapi.py#L310

After some digging what it should contain I figured adding `self.refs[schema_key] = name` fixes it:
https://github.com/marshmallow-code/apispec/blob/f075149bbd1238c1e9e17f5281d18bc0954739cd/src/apispec/ext/marshmallow/openapi.py#L108
```
108            name = get_unique_schema_name(self.spec.components, name)
109            self.refs[schema_key] = name
110            self.spec.components.schema(name, schema=schema)
```

**Comment by lafrech** [comment]
When registering the schema

    self.spec.components.schema(name, schema=schema)

the `schema_helper` from the `MarshmallowPlugin` does add the schema to the refs.

I can't reproduce this issue.

**Comment by 2nv2u** [comment]
Sorry for the late reply, I have no clue what was wrong, but I reinstalled everything and the problem seems gone.
I do however feel that it's probably nicer to add method for manipulating internals in other classes.
