### ISSUE TITLE
Dynamically loading marshmallow schemas from spec? 

### ISSUE THREAD

**Issue by abunuwas** [marshmallow-code/apispec#598]
I've been using this library for a while and enjoying it so far, so thanks for putting in the effort to maintain it!

I love the ability to generate specifications from code. I was wondering whether it'd be within the scope of this library to do the reverse as well, i.e. generate schema models from a specification? For example, when using marshmallow, I could provide the specification for a model directly from the OpenAPI specification. I was wondering whether it'd be within the scope of this library to do something like that? And just to make sure I'm not making a wrong assumption: this is not possible in marshmallow right?

**Comment by lafrech** [comment]
Hi. Thanks for the nice feedback.

Marshmallow is not tied with OpenAPI. To my knowledge, the only OpenAPI related library in the marshmallow ecosystem would be apispec (and libs built upon it, like flask-apispec or flask-smorest).

The feature you're suggesting might be achievable. I don't think it would share much code with apispec itself. I would do it in a separate library. You may want to use apispec in the tests to check how the translation round-trips.

**Comment by abunuwas** [comment]
hi @lafrech thanks for your response, that makes perfect sense!
