### ISSUE TITLE
Schema Refs

### ISSUE THREAD

**Issue by martinlatrille** [marshmallow-code/apispec#60]
Today, to add a ref to a Schema from a Schema's nested field, we must add a `ref` parameter, as such:

```
cat_with_ref = fields.Nested(CategorySchema, ref='Category', description="A category")
```

To me, it looks like we're repeating `Category` (which is gettable by removing `Schema` from the `CategorySchema` name).

I think we should do it the other way around: automatically add a ref such as `#/definitions/Category` for any `fields.Nested(CategorySchema)`, unless `use_refs=false` is passed to the APISpec.

What do you think ?

**Comment by sloria** [comment]
Inferring `ref` from the nested field name feels is probably more magic than it's worth. Not all users will follow the "<Something>Schema" convention. Explicit is better than implicit in this case.
