### ISSUE TITLE
Use a Marshmallow schema as GET query parameters

### ISSUE THREAD

**Issue by stevesmit** [marshmallow-code/apispec#611]
Hi there

In my API I use marshmallow schemas for the inputs to the routes, to handle the validation etc. In the actual route, I simply deserialise and validate the given URL parameters using the relevant marshmallow schema:

```
schema = GetObjectSchema()
data = schema.load(request.args)
```

Now I have no idea how to write the docstring YAML for this endpoint so that it uses the schema to generate the list of parameters. 

I tried the following docstring:

```
    """An endpoint.
    ---
    get:
      description: Get an object
      parameters: GetObjectSchema
      responses:
        200:
          content:
            application/json:
              schema: AnObjectSchema
    """
```

But this produces the following (just part of the output):

```
get:
      description: Get an object
      parameters:
        - $ref: '#/components/parameters/G'
        - $ref: '#/components/parameters/e'
        - $ref: '#/components/parameters/t'
        - $ref: '#/components/parameters/O'
        - $ref: '#/components/parameters/b'
        - $ref: '#/components/parameters/j'
        - $ref: '#/components/parameters/e'
        - $ref: '#/components/parameters/c'
        - $ref: '#/components/parameters/t'
        - $ref: '#/components/parameters/S'
        - $ref: '#/components/parameters/c'
        - $ref: '#/components/parameters/h'
        - $ref: '#/components/parameters/e'
        - $ref: '#/components/parameters/m'
        - $ref: '#/components/parameters/a'
      responses:
        '200':
```

Clearly this isn't quite right xD. I saw that in the documentation there is a `spec.components.parameter` function as opposed to a `spec.components.schema` so I'm sure it must be possible, I just can't work out how to do it via the YAML docstring.

**Comment by Bangertm** [comment]
The value of `parameters` needs to be an array of OpenAPI parameter objects as defined [here](https://apispec.readthedocs.io/en/latest/api_ext.html#apispec.ext.marshmallow.schema_resolver.SchemaResolver.resolve_parameters). So change your yaml to be: 
```yaml
parameters:
  - in: query
    schema: GetObjectSchema
```

**Comment by stevesmit** [comment]
@Bangertm Thank you that initially didn't work and I got the error below:

```
Traceback (most recent call last):
  File ".../documentation/generate_spec.py", line 27, in <module>
    spec.path(view=api.routes.get_taxonomy)
  File "...\lib\site-packages\apispec\core.py", line 280, in path
    plugin.operation_helper(path=path, operations=operations, **kwargs)
  File "...\lib\site-packages\apispec\ext\marshmallow\__init__.py", line 200, in operation_helper
    for response in operation.get("responses", {}).values():
AttributeError: 'NoneType' object has no attribute 'values'
```

But it was solved by creating the docstring again from scratch. I suspect the issue was with the indents in the yaml section of the docstring. This is what the working version looks like for posterity:

```
def get_object() -> Response:
    """An endpoint.
    ---
    get:
      description: Get an object
      parameters:
        - in: query
          schema: GetObjectSchema
      responses:
        200:
          content:
            application/json:
              schema: AnObjectSchema
    """
```

**Comment by Bangertm** [comment]
Yes it was the indentation. You originally had the equivalent of `responses: None`, which was causing it to throw an error.
