### ISSUE TITLE
Question: How does apispec compare with flask-swagger?

### ISSUE THREAD

**Issue by MartinThoma** [marshmallow-code/apispec#619]
The [flask-swagger](https://pypi.org/project/flask-swagger/) package expects a route to have a docstring which looks like this:

```python
"""
        Create a new user
        ---
        tags:
          - users
        definitions:
          - schema:
              id: Group
              properties:
                name:
                 type: string
                 description: the group's name
        parameters:
          - in: body
            name: body
            schema:
              id: User
              required:
                - email
                - name
              properties:
                email:
                  type: string
                  description: email for user
                name:
                  type: string
                  description: name for user
                address:
                  description: address for user
                  schema:
                    id: Address
                    properties:
                      street:
                        type: string
                      state:
                        type: string
                      country:
                        type: string
                      postalcode:
                        type: string
                groups:
                  type: array
                  description: list of groups
                  items:
                    $ref: "#/definitions/Group"
        responses:
          201:
            description: User created
"""
```

Flask-swagger is then used like this:

```
from flask import Flask, jsonify
from flask_swagger import swagger
from flask_swagger_ui import get_swaggerui_blueprint

app = Flask(__name__)

swagger_ui_bp = get_swaggerui_blueprint("/docs", "/spec")
app.register_blueprint(swagger_ui_bp)

@app.route("/spec")
def spec():
    swagger_obj = swagger(app)
    return jsonify(swagger_obj)
```

with that, it generates a OpenAPI 2.0 file which is used by flask_sagger_ui to create a swagger documentation page.

This looks very similar to what I see in the [apispec](https://pypi.org/project/apispec/) project.

Does somebody maybe use both and could point out differences? How much work would the transition from flask_swagger to apispec be?

**Comment by lafrech** [comment]
I can't comment about flask_swagger.

apispec has a plugin mechanism allowing to build the spec from inputs other than YAML. In fact, I never write a single piece of YAML to document my APIs.

The documentation can be passed programatically. The marshmallow plugin describes the I/O automatically. A dedicated web-framework plugin can pickup path arguments (see https://github.com/marshmallow-code/apispec-webframeworks).

Using [flask-smorest](https://github.com/marshmallow-code/flask-smorest), most if not all the doc construction work is provided by the framework and done automatically.

**Comment by lafrech** [comment]
Closing this is not an issue. No pb if people want to comment below.
