### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'map_to_openapi_type'

### ISSUE THREAD

**Issue by aprilahijriyan** [marshmallow-code/apispec#623]
I tried to use the following code https://github.com/jmcarp/flask-apispec/issues/122 to create a marshmallow field for the file type.

```python

file_plugin = MarshmallowPlugin()
@file_plugin.map_to_openapi_type("file", None)
class FileField(fields.Raw):
    pass
```

Output:

```
File "/home/titiw/projects/hypexblog/backend/venv/lib/python3.7/site-packages/apispec/ext/marshmallow/__init__.py", line 146, in map_to_openapi_type
    return self.converter.map_to_openapi_type(*args)
AttributeError: 'NoneType' object has no attribute 'map_to_openapi_type'
```

**Comment by lafrech** [comment]
That snippet is outdated.

You're using your `MarshmallowPlugin` instance before calling `init_spec`. You need to create an `APISpec` first. At init, it will call your plugin's `init_spec`.

**Comment by aprilahijriyan** [comment]
Could you please provide me with a sample code to work with this?

**Comment by aprilahijriyan** [comment]
Hi, I don't understand how I can add a custom field to the apispec.

**Comment by aprilahijriyan** [comment]
Documentation: https://apispec.readthedocs.io/en/latest/api_ext.html#apispec.ext.marshmallow.MarshmallowPlugin.map_to_openapi_type

I'm trying to understand your code. Starting from:

* https://github.com/marshmallow-code/apispec/blob/5762c831fccf9d8dedcdfb901d106c02addc278b/src/apispec/ext/marshmallow/__init__.py#L119

Ends on:

* https://github.com/marshmallow-code/apispec/blob/5762c831fccf9d8dedcdfb901d106c02addc278b/src/apispec/ext/marshmallow/openapi.py#L37

I can't find the `map_to_openapi_type` method in the `converter`.
Is this a bug?

**Comment by aprilahijriyan** [comment]
Sorry, my mistake. This has worked so far. 😆
