### ISSUE TITLE
Generate Marshmallow classes from Open API

### ISSUE THREAD

**Issue by ghost** [marshmallow-code/apispec#626]
Hi there,

I'm not sure if this has been asked before, but I was wondering if you had previously considered generating Marshmallow Schema classes from OpenAPI spec - basically the reverse operation for your `to_json` and `to_yaml` methods and leveraging something like the Marshmallow `from_dict` method.

I'd really appreciate your thoughts on the pros and cons and perhaps some code where you've tried to do something similar.

Thanks for all the good work!!

**Comment by lafrech** [comment]
I think this was asked before. Can't find the source.

This would be interesting but as of today we think it would be out of scope.

Of course, if someone manages to do that, we'll be very interested, so please keep us posted.
