### ISSUE TITLE
How to document schema fields?

### ISSUE THREAD

**Issue by bkircher** [marshmallow-code/apispec#632]
Hope this is not a too stupid question but I'm struggling to get this to work.

How would I document individual fields of a marshmallow schema? Class attributes do not have docstrings directly attached to it.

**Comment by lafrech** [comment]
You may pass attributes as metadata.

```py
choice = fields.Int(metadata={"description": "Some choice", "enum": [1, 2], "x-some-property": "Some value"})
```

Valid properties are:

https://github.com/marshmallow-code/apispec/blob/cca21f2be7e9ea813428d9f2d62d42785ce7b854/src/apispec/ext/marshmallow/field_converter.py#L44-L73

plus properties prepended with "x-".

**Comment by lafrech** [comment]
Sorry for the delay. I hope this helps. Feel free to comment here if you need more help.
