### ISSUE TITLE
Supported vs End Of Life (EOL) versions? 

### ISSUE THREAD

**Issue by aaronk-cb** [marshmallow-code/apispec#653]
What versions of apispec are supported vs what versions are end of life (EOL)?

**Comment by lafrech** [comment]
We generally only support latest version.

There could be exceptions: if a major version introduced huge changes, we probably wouldn't object to merge and release a bugfix in former major version, but the general rule is only latest version is supported.

**Comment by aaronk-cb** [comment]
Thanks @lafrech !  Would that be 4.x or 4.3.x?

Does that mean that if a vulnerability were reported in a dependency, you'd only check if the latest version is impacted?

**Comment by lafrech** [comment]
That would be 4.3.x. The rationale being that supporting all 4.x would be more effort while nothing should prevent the user from moving to 4.3.x from 4.x.

In fact even major version have limited breaking changes so same rationale applies for not supporting 3.x.

> Does that mean that if a vulnerability were reported in a dependency, you'd only check if the latest version is impacted?

Yes, I guess so.

(There should be limited risk in apispec anyway, as opposed to marshmallow or webargs who actually parse user input, but the question remains relevant.)

**Comment by aaronk-cb** [comment]
Thank you!  Much appreciated!

**Comment by lafrech** [comment]
No pb.
