### ISSUE TITLE
Setting Meta.unknown=EXCLUDE should leave `additionalProperties` unset.

### ISSUE THREAD

**Issue by kupuguy** [marshmallow-code/apispec#659]
Release 4.4.0 includes a change that sets `additionalProperties: false` when `Meta.unknown` is not `INCLUDE`.

The `Meta.unknown` field has 3 possible values: `RAISE`, `INCLUDE`, and `EXCLUDE`. The new change sets additionalProperties correctly for `RAISE` (additional properties are an error) and `INCLUDE` (additional properties are permitted) but `EXCLUDE` means additional fields may exist but will be removed without generating an error and this change means additional fields now generate an error.

Using INCLUDE and ignoring any extra fields isn't a workaround as (for example) when generating a type library for a typescript client the `additionalProperties: True` adds `[name: string]: any;` to the interface.

Ideally `unknown=RAISE` should set `additionalProperties: false`, `unknown=INCLUDE` should set `additionalProperties: true` and `unknown=EXCLUDE` should not set `additionalProperties` at all. This would mean connexion will still pass through any additional properties rather than erroring but I don't think there's a way to tell connexion to strip unknown fields.

**Comment by jonadaly** [comment]
Note that 4.4.0 is a breaking change as a result of the above, if you use `Meta.unknown` of `EXCLUDE`.

The result of the update is that validation has become stricter (rejecting requests containing unknown fields), which could break people's APIs if they don't realise.

**Comment by lafrech** [comment]
@kupuguy Thanks for the detailed report. Would you have the time to work on a PR?

@jonadaly I don't think this change would break an API. It only applies to the doc, not to the actual validation. I don't see it as a breaking change. It only makes the doc more precise. Well, it was supposed to, but it seems the `EXCLUDE` case was overlooked.

**Comment by jonadaly** [comment]
It seems to applies to the validation as well - because `additionalProperties: false` means that any request with additional unknown fields gets rejected.

We are using apispec with connexion to validate requests, and connexion is raising HTTP 400 errors where previously it was allowing requests with unknown fields.

(It seems to me that setting unknown=EXCLUDE should still allow requests to be made with unknown extra fields - this was the case previously, but isn't any more with 4.4.0)

**Comment by jonadaly** [comment]
(It seems to me that if you set unknown=EXCLUDE, requests with extra unknown fields should be allowed, which was the case previously but isn't with 4.4.0)

**Comment by lafrech** [comment]
@jonadaly there must be another change. apispec doesn't do validation, it only documents the API. Validation takes place in marshmallow/webargs. Please double check lib versions.

**Comment by jonadaly** [comment]
Yes I understand apispec doesn't do validation, but it is documenting the API differently - which causes any validation based on openapi (e.g. connexion/marshmallow) to change behaviour.

Before 4.4.0, setting unknown=EXCLUDE had no effect in the openapi spec.
After 4.4.0, setting unknown=EXCLUDE causes additionalProperties to be set to false, which doesn't seem correct - hence me saying it appears to be a breaking change.

Regardless, implementing @kupuguy's suggestion should resolve the problem.

**Comment by lafrech** [comment]
OK, I guess I don't understand your workflow. Are you generating an openapi doc with apispec, then using that doc to generate marshmallow schemas?

**Comment by jonadaly** [comment]
We are generating an openapi doc with apispec, then pointing connexion at the spec to perform validation of requests: https://github.com/zalando/connexion

**Comment by lafrech** [comment]
Ah OK, I didn't know connexion. This must be quite an uncommon use case for apispec (but legit nonetheless).

**Comment by jonadaly** [comment]
We've been using this approach for 2 years for flask apps. It's really great :)

It's also interesting to note that FastAPI has since come along and does something very similar behind the scenes: https://fastapi.tiangolo.com/

**Comment by lafrech** [comment]
Closed in #663.
