### ISSUE TITLE
Marshmallow 3.12 schema with `fields` property produce error

### ISSUE THREAD

**Issue by Reskov** [marshmallow-code/apispec#673]
Marshmallow added Fields be accessed by name as Schema attributes 

I have a schema like this 

```python
import marshmallow as ma

class Schema(ma.Schema):
    fields = ma.fields.List(ma.fields.Int)
```

Produces error 

```
 File "/venv/lib/python3.9/site-packages/apispec/ext/marshmallow/openapi.py", line 127, in schema2parameters
    fields = get_fields(schema, exclude_dump_only=True)
  File "/venv/lib/python3.9/site-packages/apispec/ext/marshmallow/common.py", line 56, in get_fields
    return filter_excluded_fields(fields, Meta, exclude_dump_only=exclude_dump_only)
  File "/venv/lib/python3.9/site-packages/apispec/ext/marshmallow/common.py", line 90, in filter_excluded_fields
    for key, value in fields.items()
AttributeError: 'List' object has no attribute 'items'
```

https://marshmallow.readthedocs.io/en/stable/changelog.html#id2

`get_fields` function gets `fields` schema attribute:
https://github.com/marshmallow-code/apispec/blob/dev/src/apispec/ext/marshmallow/common.py#L46

Can we eliminate this?

**Comment by lafrech** [comment]
This should be fixed by changing the test in `get_fields` for something like `if isinstance(schema, type)` as in

https://github.com/marshmallow-code/apispec/blob/cca21f2be7e9ea813428d9f2d62d42785ce7b854/src/apispec/ext/marshmallow/common.py#L13-L23
