### ISSUE TITLE
Is it possible to display schema's property on swaggerui ?

### ISSUE THREAD

**Issue by KeyzaneX** [marshmallow-code/apispec#676]
Hello,

I'm trying do use apispec to documentate a small API but I have a problem ,
My schemas are not fully documented
I only have the name of the schema and not the properties.

```
class FishSchema(Schema):
    name = fields.String()
    color = fields.String()
    race = fields.String()
    waterbreathing = fields.Bool(default=True, required=False, missing=False)
    birthday = fields.DateTime()
    scales = fields.Integer()
    babies = fields.List(fields.Nested(lambda: FishSchema),required=False, missing=None)

```
```
spec = APISpec(
    title="SPA",
    version="1.0.0",
    openapi_version="3.0.3",
    info=dict(description="A minimal API"),
    plugins=[FlaskPlugin(), MarshmallowPlugin()],
)

spec.components.schema("Fish", schema=FishSchema)
```

```
@api.route('/polypets/add', methods=['POST'])
class createPet(Resource):
    def post (self):
        """polypetadd view
        ---
        description: addpolypet
        responses:
          200:
            content:
              application/json:
                schema: Fish
        """
        pets = MyPetSchema().load(request.get_json(),many=True)
        print(spec.to_yaml())
        return MyPetSchema().dump(pets, many=True)

method_view = createPet.as_view("Fish")
app.add_url_rule("/polypets/add", view_func=method_view)
with app.test_request_context():
    spec.path(view=method_view)```
```

on swagger : https://prnt.sc/14op3a7
When I print spec.to_yaml on shell : https://prnt.sc/14opd09

**Comment by lafrech** [comment]
I can't comment on the UI but the generated spec looks good to me. The properties are in the schema in the components section.

I don't know what you expect form the UI. Note that the schema definition is recursive. Perhaps the UI doesn't work great with this. Just a hint, I have no idea.

I'm afraid I can't provide much more help. I believe the spec is correct, so this is a Swagger-UI question.

[BTW, please don't post screenshots for text output.]

**Comment by E-Kalla** [comment]
> I can't comment on the UI but the generated spec looks good to me. The properties are in the schema in the components section.
> 
> I don't know what you expect form the UI. Note that the schema definition is recursive. Perhaps the UI doesn't work great with this. Just a hint, I have no idea.
> 
> I'm afraid I can't provide much more help. I believe the spec is correct, so this is a Swagger-UI question.
> 
> [BTW, please don't post screenshots for text output.]

Hello,

thanks for reply
Sorry I forgot to say I have no components section on swagger UI
https://prnt.sc/15l84vq

Did I miss something ?
