### ISSUE TITLE
How to deal with examples for responses, requestBody, parameters?

### ISSUE THREAD

**Issue by SomeAkk** [marshmallow-code/apispec#683]
For example, I add examples like that:

```python
@app.route("/random")
def random_pet():
    """A cute furry animal endpoint.
    ---
    get:
      description: Get a random pet
      security:
        - ApiKeyAuth: []
      req:
        description: "description"
        content:
          application/json:
            schema: Pet
            examples: ... #10-20 lines
      responses:
        200:
          content:
            application/json:
              schema: Pet
              examples: ... #10-20 lines
        400:
          content:
            application/json:
              schema: Pet400
              examples: ... #10-20 lines
        403:
          content:
            application/json:
              schema: Pet403
              examples: ... #10-20 lines
        409:
          content:
            application/json:
              schema: Pet409
              examples: ... #10-20 lines
    """
    pet = get_random_pet()
    return PetSchema().dump(pet)
```

So, finally we have over 100+ lines in swagger docstring. To do that in code - bad idea.
Can we move doc to yaml/json file and connect it through decorator like that:
```python
@swagger("swagger/random_pet.yaml")
@app.route("/random")
def random_pet():
  """A cute furry animal endpoint.
  """
  pet = get_random_pet()
  return PetSchema().dump(pet)
```

**Comment by lafrech** [comment]
This is not possible currently. And in fact keeping the doc close to the code is a way to keep it in sync, so I'm lukewarm to add features moving doc information far away from view functions.

This said, you may define responses and other components somewhere else and only reference themin view func docstrings.

Also, you may want to consider using a framework that auto-documents schemas and all, such as flask-smorest or APIFlask.

If you implement the feature your propose above, please share it here, it might be useful to someone else.

**Comment by SomeAkk** [comment]
In general, we are using aiohttp+marshmallow, so if you can suggest something that can operate with marshmallow schemas and aiohttp routes and create docs from it in swagger except apispec - it will be great.

About feature implementing: we had plugin for marshmallow from your team, and in another side [not yours plugin for aiohttp](https://github.com/maximdanilchenko/aiohttp-apispec) that seems not supported at all (if look at last commit date). Also this plugin has overhead (as for my opinion). So for that i need to implement that feature not only for apispec, but and for aiohttp plugin. I will think about it, but I will not promise anything.

Can you official support aiohttp like Flask (by module creating)?

**Comment by aalvrz** [comment]
This might be of help: https://github.com/ovh/python-apispec-fromfile

**Comment by SomeAkk** [comment]
@aalvrz thx, but looked at it yesterday - it is not compatible with [old aiohttp plugin](https://github.com/maximdanilchenko/aiohttp-apispec) because of format of yaml file.
