### ISSUE TITLE
Nullable in OAS 3.1 rendered as "'null'" string instead of "null"

### ISSUE THREAD

**Issue by mjpieters** [marshmallow-code/apispec#689]
Nullable fields should be rendered as `"type": ["fieldType", "null"]`, not `["fieldType", "'null'"]`.

The field converter currently includes quotes around `null` _in the literal string value_, see https://github.com/marshmallow-code/apispec/blob/5cf763e04df42afddc2480991c878da928558417/src/apispec/ext/marshmallow/field_converter.py#L283

which results in JSON like this:

```json
          "created_at": {
            "type": [
              "string",
              "'null'"
            ],
            "format": "date-time",
            "readOnly": true
          },
```

or as YAML:

```yaml
       created_at:
          type:
            - string
            - '''null'''
          format: date-time
          readOnly: true
```

While the type string should be a string (and not `None` in Python, `null` in JSON or YAML), the extra quotes there are an error.

To fix, please drop the extra quotes in the value:

```python
                attributes["type"] = make_type_list(ret.get("type")) + ["null"] 
```

Also see 
- [Understanding JSON Schema: null](https://json-schema.org/understanding-json-schema/reference/null.html)
- this specific [valid specification test](https://github.com/OAI/OpenAPI-Specification/blob/54edcf039c9854dcbc4feac1b1990c21972f3ca5/tests/v3.1/pass/mega.yaml#L45) in the OpenAPI specification repository.

**Comment by lafrech** [comment]
I can't remember precisely, but it is very possible that I'm the one who put those quotes and I did it on purpose, but I guess I was wrong.

Thanks for the fix.
