### ISSUE TITLE
Flask extension does not support application root

### ISSUE THREAD

**Issue by deckar01** [marshmallow-code/apispec#69]
The flask extension only outputs the route path, but `flask.url_for()` takes into consideration that the path should be prefixed with the configured `APPLICATION_ROOT` path. [apispec/ext/flask.py#L58](https://github.com/marshmallow-code/apispec/blob/1076180/apispec/ext/flask.py#L58)
- http://flask.pocoo.org/docs/0.10/config/#builtin-configuration-values
- https://github.com/pallets/flask/blob/9f1be8e/flask/helpers.py#L309
- https://github.com/pallets/flask/blob/2bf477c/flask/app.py#L1761

**Comment by sloria** [comment]
Thanks for reporting. 

I would welcome a PR for this.

**Comment by deckar01** [comment]
Looking into the implementation. :eyeglasses: 

I would like to lean on the `url_adapter` interface as much as possible to avoid replicating the internal implementation of flask and insulate the extension against future changes.
