### ISSUE TITLE
Document the use of apispec[marshmallow]

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/apispec#707]
See https://github.com/marshmallow-code/apispec/pull/706#issuecomment-914426249.

**Comment by Sinclert** [comment]
_(Continuing the conversation here)_

Thanks for the issue tracking @lafrech 😄 

I would say both solutions work. Either:
- The installation of `apispec[marshmallow]` is specified on the [README](https://github.com/marshmallow-code/apispec/blob/dev/README.rst) and [this page of the documentation](https://apispec.readthedocs.io/en/latest/using_plugins.html#example-flask-and-marshmallow-plugins).
- The dependency `marshmallow` is moved to the `install_requires` section of the [setup.py](https://github.com/marshmallow-code/apispec/blob/dev/setup.py).

I, personally, am a bigger fan of the **second one**, given that.... most? examples provided in the docs involve `marshmallow`. However, you are the maintainer, so it is your choice.

**Comment by lafrech** [comment]
I opened #708 to discuss second option.

Docs still need improvement for now.
