### ISSUE TITLE
[RFC] Make marshmallow a hard dependency

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/apispec#708]
Pros:

- Makes it easier to require a marshmallow version since marshmallow can be in `install_requires`. Avoids user being caught with a too old marshmallow version because of not using `apispec[marshmallow]` (#706).

Cons:

- Installs marshmallow for people not using it.

Are there people using apispec without marshmallow today?

In any case, that would happen in the next major, and meanwhile we can still improve doc about `apispec[marshmallow]` (#707).

I have no strong feeling either way. Documentation, once improved, should be enough, and people should read changelogs, especially when upgrading to major versions.

OTOH, if all usage examples require marshmallow and the lib is almost worthless without it, then why bother keeping it optional?

@sloria @Bangertm

**Comment by sloria** [comment]
I've no strong opinion either way. My gut feeling w/o any empirical evidence is that the majority of apispec users will already be using marshmallow.

Agreed that we should update the docs per #707 in the short term.

**Comment by sripathivenky** [comment]
Any update !!

**Comment by chey** [comment]
I personally would prefer this module remain agnostic as stated in your features.

**Comment by lafrech** [comment]
OK. @chey is this a matter of principle or do you actually use apispec without marshmallow? Just curious. Again, no strong opinion, here.

**Comment by chey** [comment]
> OK. @chey is this a matter of principle or do you actually use apispec without marshmallow? Just curious. Again, no strong opinion, here.

Both i would say. But yes, i do use apispec without marshmallow.

**Comment by lafrech** [comment]
Nice to know. Thanks for the feedback.

**Comment by mofr** [comment]
I'm going to integrate the apispec with [winter framework](https://github.com/WinterFramework/winter/), which is not dependent on marshmallow. Dataclasses are at the core instead. So I really would prefer to have apispec agnostic and pluggable as stated as a feature.

**Comment by lafrech** [comment]
OK, let's keep things as they are.
