### ISSUE TITLE
Passing placeholder in dataclasses field metadata

### ISSUE THREAD

**Issue by arfaoui47** [marshmallow-code/apispec#709]
To pass description for OpenAPI and using dataclasses:
`data: str = field(metadata={'description': 'data description'}`

for passing placeholder values for OpenAPI which method can we use?

**Comment by arfaoui47** [comment]
Can use: `doc_default`
`data: str = field(metadata={'description': 'data description', 'doc_default': 'placeholder for docs'}`

**Comment by lafrech** [comment]
`doc_default` was renamed to `default` in 5.0.0. See CHANGELOG.
