### ISSUE TITLE
How to handle multiple spec files per api version?

### ISSUE THREAD

**Issue by LucasHartridge** [marshmallow-code/apispec#719]
Hi all :wave: 

I was digging into the docs, trying to find some example to generate multiple spec files, 1 per API version. 
After this, I would expect to call api/v1.0 or api/v1.1 in the Swagger UI to load one or another spec file

The idea of having multiple spec files is to have documented all the API versions that could be used, until the oldest one will be deprecated 

Can you provide me some help here?

Thanks!

**Comment by lafrech** [comment]
I suppose you can achieve this by creating several `APISpec` instances and passing each instance the routes it should document.

APISpec.path shouldn't modify the values it is passed so it should be safe to pass the same route to several instances.

```py
spec_1_0.path(view=random_pet)
spec_1_1.path(view=random_pet)
```

Is there anything you would like apispec to do?

We could try to support

```py
spec.path(view=random_pet, versions=["1.0", "1.1"])
spec.to_dict(version="1.0")
```

I'm open to this if someone wants to look into it and propose an implementation.

**Comment by LucasHartridge** [comment]
Thanks for the reply @lafrech. 

The option proposed by you is clearly an improvement, but I don't see any problem with the current implementation
