### ISSUE TITLE
ApiDoc Generation failing due to missing name parameter, Resolve Parameters bug?

### ISSUE THREAD

**Issue by arthurvanduynhoven** [marshmallow-code/apispec#732]
I have a schema which contains all my query parameters for my endpoint (pagination, filtering, etc)

Based on resolve_parameters I expect it to work as documented. The Marshmallow Plugin will auto expand all the fields in the schema and result with a list of parameters.

https://apispec.readthedocs.io/en/latest/api_ext.html#apispec.ext.marshmallow.schema_resolver.SchemaResolver.resolve_parameters

So when I try to generate my documentation I get an error stating `name` property must exist. But from the resolve_parameters it should not be needed (as if I try to add it, then a single query parameter is created as a nested json object).

Am I understanding/configuring something incorrectly?

# Dependency Versions
```
marshmallow==3.14.1
apispec==5.1.1
apispec-webframeworks==0.5.2
Flask==2.0.2
```

# Example layout of doc generation
```
from apispec import APISpec
from apispec.ext.marshmallow import MarshmallowPlugin
from apispec_webframeworks.flask import FlaskPlugin

def docs():
  spec = APISpec(
        title=SERVICE_API_SPEC_TITLE,
        info=dict(description=SERVICE_API_SPEC_DESCRIPTION),
        version=SERVICE_API_SPEC_VERSION,
        openapi_version=OPENAPI_VERSION,
        plugins=[FlaskPlugin(), MarshmallowPlugin()],
        security=[
            {"oAuth": []},
            {"bearerAuth": []},
        ]
    )
    
    spec.components.schema(
        "QueryParamsSchema", schema=QueryParamsSchema)
        
     spec.components.parameter(
        'customerId',
        'path',
        component={
            'name': 'customer_id',
            'description': 'customer name',
            'schema': {
                'type': 'string',
            }
        }
    )
        
     for rule in sorted(current_app.url_map.iter_rules(), key=lambda x: str(x)):
        if str(rule).startswith('/my_app'):
            spec.path(view=current_app.view_functions[rule.endpoint])
    return spec.to_yaml()
```

# Example doc string in flask endpoint
```
parameters:
          - customerId
          - in: query
             schema: $ref:  '#/components/schemas/QueryParamsSchema'
```

**Comment by lafrech** [comment]
Can you please paste the error traceback?

**Comment by Bangertm** [comment]
In the second parameter, the value of the `schema` key is a reference object. It should be a string that resolves to a marshmallow schema, i.e. ```schema: "QueryParamsSchema"``` like in the example. 

Also note that the call to `spec.components.schema` to manually add this schema to the spec is not necessary and is probably not desired given that the intent is to expand this schema as query parameters.

**Comment by lafrech** [comment]
> In the second parameter, the value of the schema key is a reference object. It should be a string that resolves to a marshmallow schema, i.e. schema: "QueryParamsSchema" like in the example.

Oh, right. This is the reason for the missing name property error. Since the schema is passed as a dict ({"$ref": ...}), it is assumed to be a property, not a ref. Refs should be passed as just strings.

I didn't realize this part of the OP was a dosctring, for some reason I thought it was an excerpt of the generated doc so the question didn't make much sense to me.

**Comment by arthurvanduynhoven** [comment]
Thanks for the help. It is now working as described by not specifying it as `$ref`

One thing I am noticing, the final openapi spec output, the query parameter name is not using the defined Marshmallow field `data`/`attribute` value, but the code field name. Is this expected? or a bug/misconfiguration?

For example I would expect to see `sortBy` in the api spec not `sort_by`.

```
class PaginationParams(Schema):
  sort_by = field.string(
         data='sortBy',
         description='Sort by a given property',
         example='id'
   )
```

**Comment by lafrech** [comment]
It should be `data_key`, not `data`.

**Comment by arthurvanduynhoven** [comment]
> It should be `data_key`, not `data`.

🤦 

Thanks!
