### ISSUE TITLE
Document filter query params with marshmallow or webargs

### ISSUE THREAD

**Issue by caseydm** [marshmallow-code/apispec#734]
I am trying to use apispec to document query parameters like this:

`/?filter=year:2020,institution_id=559823&search=title:covid-19&details=true`

Any idea how to handle a list of key value pairs like this in a schema? This is what I tried to do but the result in the documentation was filter = 'array of object'.

```
class WorksQueryFilter(Schema):
    year = fields.Int()
    institution_id = fields.Int()

class WorksQuerySchema(Schema):
    filter = fields.Nested(WorksQueryFilter)

@blueprint.route("/")
def index():
    """
    ---
    get:
      description: Search and filter works
      parameters:
      - in: query
        schema: WorksQuerySchema
      responses:
        200:
          description: Return works
          content:
            application/json:
              schema: WorksSchema
    """
```

**Comment by lafrech** [comment]
This is your own format, so I'm afraid you're on your own, here.

Unless I'm mistaken, there is nothing in OpenAPI for this use case.

The typical case would be passing filter elements directly as kwargs but I guess you don't want to change this:

    /?year=2020&institution_id=559823&search=title:covid-19&details=true

**Comment by caseydm** [comment]
Ok thanks for replying so quickly!

**Comment by caseydm** [comment]
One more question - do you think there is a way to use marshmallow to validate and load params with deepObject and explode: true? 

So the endpoint would be:

`?filter[year]=2020&filter[ror_id]=asdofi`

Similar to this:

```
- in: query
  name: filter
  style: deepObject
  explode: true
  schema:
    type: object
    description: Filter results.
    properties:
      year:
        type: int
        description: filter by year
        example: asdf
      ror_id:
        type: string
        description: filter by ROR ID
    example:
      year: 2020
      ror_id: 23429wf
```
