### ISSUE TITLE
Add typing

### ISSUE THREAD

**Issue by kasium** [marshmallow-code/apispec#745]
Hey guys,

thanks for creating this package. Short question: Are you open to add type hints (typing) to this package?
Basically. I would like mypy to check the usage and currently this is not possible.

I'm also open to create a PR.

**Comment by lafrech** [comment]
Contrib very welcome!

You may build upon #726. I can't work on this right now.

Thanks.

**Comment by kasium** [comment]
@lafrech I created a new PR since I couldn't push in the old one. I copied you previous work and will continue
