### ISSUE TITLE
release 5.2.0: The annotations for path in `path()` have changed

### ISSUE THREAD

**Issue by chey** [marshmallow-code/apispec#764]
https://github.com/marshmallow-code/apispec/blob/eda2887adb8baf414b280ce5bd5528e9614eaa66/src/apispec/core.py#L470-L482

I'm getting annotation errors with this release.

```
error: Argument "path" to "path" of "APISpec" has incompatible type "str"; expected "Optional[Dict[Any, Any]]"
```

**Comment by lafrech** [comment]
@chey see #765.
