### ISSUE TITLE
Add format for marshmallow.fields.Decimal

### ISSUE THREAD

**Issue by dolamroth** [marshmallow-code/apispec#767]
Currently, `DEFAULT_FIELD_MAPPING` defines the following (type, format) for Decimal field:

```
marshmallow.fields.Decimal: ("number", None)
```

It would be valuable to explicitly add format "decimal": `("number", "decimal")`

Popular JSON encoders, such as simplejson or Django's DjangoJSONEncoder, stringify Decimal when serializing to JSON, as opposed to other numeric types.

**Comment by lafrech** [comment]
Looks like "decimal" is not a valid OpenAPI data type: https://spec.openapis.org/oas/latest.html#data-types.

(In any case, the user is free may override the default mapping.)

**Comment by dolamroth** [comment]
Yet, there is a need to differentiate these, because decimal is the only numeric type, that may be serialized as string. 

As an example, drf-yasg (library, that provides Redoc for Django with Rest Framework) does exactly that: https://github.com/axnsan12/drf-yasg/blob/b99306f71c6a5779b62189df7d9c1f5ea1c794ef/src/drf_yasg/openapi.py#L48

By the way. I've tried to make a pull-request, but it seems I don't have permissions, so I made request in my fork. You may consider it, if you please: https://github.com/dolamroth/apispec/pull/1

**Comment by lafrech** [comment]
For completeness sake, here's the code in drf-yasg:

```py
# officially supported by Swagger 2.0 spec
FORMAT_DATE = "date"  #:
FORMAT_DATETIME = "date-time"  #:
FORMAT_PASSWORD = "password"  #:
FORMAT_BINARY = "binary"  #:
FORMAT_BASE64 = "bytes"  #:
FORMAT_FLOAT = "float"  #:
FORMAT_DOUBLE = "double"  #:
FORMAT_INT32 = "int32"  #:
FORMAT_INT64 = "int64"  #:


# defined in JSON-schema
FORMAT_EMAIL = "email"  #:
FORMAT_IPV4 = "ipv4"  #:
FORMAT_IPV6 = "ipv6"  #:
FORMAT_URI = "uri"  #:


# pulled out of my ass
FORMAT_UUID = "uuid"  #:
FORMAT_SLUG = "slug"  #:
FORMAT_DECIMAL = "decimal"
```

For now, we've always been sticking to OpenAPI/swagger, making no assumption about user code.

Note that you may override this in your app using [`map_to_openapi_type`](https://apispec.readthedocs.io/en/latest/api_ext.html#apispec.ext.marshmallow.MarshmallowPlugin.map_to_openapi_type).
