### ISSUE TITLE
Schema field Order is alphabetical, instead of using Marshmallow's order

### ISSUE THREAD

**Issue by mkmoisen** [marshmallow-code/apispec#782]
In Marshmallow, you can order the fields by using `class Meta:    ordered = True`, like:

```
class FooSchema(Schema):
    b = fields.Int()
    a = fields.int()
    class Meta:
        ordered = True

for k in FooSchema.fields():
    print(k)
````

This will output:

```
b
a
```

However, the schema generated by apispec ordered the fields alphabetically. 

Shouldn't it default to Marshmallow's natural order?

Is there any workaround to get the fields ordered correctly?

Thank you.

**Comment by lafrech** [comment]
apispec respects schema order.

You may want to double-check your code doesn't force alphabetical order (for instance, by default, Flask sorts keys when serializing json).

**Comment by lafrech** [comment]
Closing for lack of feedback. Free free to bring additional details in comments.
