### ISSUE TITLE
dump_only should add readOnly flag

### ISSUE THREAD

**Issue by itajaja** [marshmallow-code/apispec#79]
I think the semantic of `dump_only` matches the `readOnly` flag on the swagger spec. Shouldn't dump_only set that flag to true on the field?

http://swagger.io/specification/

**Comment by sloria** [comment]
Yes, I think it makes sense. I would accept a PR for this.

**Comment by itajaja** [comment]
I can do it :)

**Comment by sloria** [comment]
Thanks!

**Comment by incognick** [comment]
When dump_only is True, shouldn't this field be omitted completely from the spec as an parameter argument?
