### ISSUE TITLE
Integration tests with swagger-tools

### ISSUE THREAD

**Issue by jmcarp** [marshmallow-code/apispec#8]
I caught a few minor issues (see #6, #7) running output through the validator in swagger-tools:

```
swagger-tools validate spec.json
```

It could be helpful to add integration tests using swagger-tools to catch subtle or poorly documented issues like this. I'm down to write this if you think it would be worthwhile @sloria.

**Comment by sloria** [comment]
Yes, I think this is a very good idea.

**Comment by jmcarp** [comment]
Done in #9.
