### ISSUE TITLE
exported marshmallow Enum fields should be arrays, not CSV strings

### ISSUE THREAD

**Issue by tadams42** [marshmallow-code/apispec#806]
Hi, 

I really love new support for marshmalow Enum fields but... these are not correctly exported into OAS3 :disappointed: .

We get strings:

```json
"status": {
  "type": "string",  
  "enum": "INACTIVE, ACTIVE"
}
```

but we need lists:

```json
"status": {
  "type": "string",
  "enum": [
    "INACTIVE",  "ACTIVE"
  ]
}
```

This breaks ReDoc completelly (fails to load spec and UI), and SwaggerUI partially (loads UI, but errors into console when trying to display some object schema).

Relevant docs:

- [OpenAPI guide - enums](https://swagger.io/docs/specification/data-models/enums/)
- [OpenAPI specification Schema Object - properties](https://swagger.io/specification/#schema-object)
- [JSON Schema Validation](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-00#section-5.20)

Minimal example:

```py
import enum
import json
from apispec import APISpec
from apispec.ext.marshmallow import MarshmallowPlugin
from marshmallow import Schema, fields

spec = APISpec(
    title="Example",
    version="1.0.0",
    openapi_version="3.0.2",
    plugins=[MarshmallowPlugin()],
)

class Statuses(enum.Enum):
    INACTIVE = 0
    ACTIVE = 1

class ItemSchema(Schema):
    id = fields.Int()
    status = fields.Enum(Statuses, allow_none=False)

spec.components.schema("Item", schema=ItemSchema)

print(json.dumps(spec.to_dict(), indent=2))
```

gives us this:

```jsoh
{
  "paths": {},
  "info": {
    "title": "Example",
    "version": "1.0.0"
  },
  "openapi": "3.0.2",
  "components": {
    "schemas": {
      "Item": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "status": {
            "type": "string",
            "enum": "INACTIVE, ACTIVE"
          }
        }
      }
    }
  }
}
```

**Comment by lafrech** [comment]
Right, thanks.

Fix in #807.
