### ISSUE TITLE
What is the correct way to use add_attribute_function in the Marshmallow plugin?

### ISSUE THREAD

**Issue by mwgamble** [marshmallow-code/apispec#820]
The Marshmallow plugin's converter class has a method named `add_attribute_function`, which is used for implementing custom schema generation code. I'm confused about how to use it.

If I follow the basic example from the documentation:

```python
spec = APISpec(
    title="Gisty",
    version="1.0.0",
    openapi_version="3.0.2",
    info=dict(description="A minimal gist API"),
    plugins=[MarshmallowPlugin()],
)
```

I never get access to the plugin object, which means I can't access its `converter` property, which means I can't call `add_attribute_function`.

I could instead write the code like this:

```python
plugin = MarshmallowPlugin()
plugin.converter.add_attribute_function(my_attr_func)

spec = APISpec(
    title="Gisty",
    version="1.0.0",
    openapi_version="3.0.2",
    info=dict(description="A minimal gist API"),
    plugins=[plugin],
)
```

Unfortunately this doesn't work, because the `converter` property is `None` at the stage where it's being called.

I could do this instead:

```python
plugin = MarshmallowPlugin()

spec = APISpec(
    title="Gisty",
    version="1.0.0",
    openapi_version="3.0.2",
    info=dict(description="A minimal gist API"),
    plugins=[plugin],
)

plugin.converter.add_attribute_function(my_attr_func)
```

But the type-checker will complain at me, because `plugin.converter` could potentially be `None`, so the method call is unsafe.

I could write the code like this (to satisfy the type-checker):

```python
plugin = MarshmallowPlugin()

spec = APISpec(
    title="Gisty",
    version="1.0.0",
    openapi_version="3.0.2",
    info=dict(description="A minimal gist API"),
    plugins=[plugin],
)

if plugin.converter:
    plugin.converter.add_attribute_function(my_attr_func)
```

But this smells really badly. If nothing else, it gives the impression that the attribute function is optional, when it's not.

Am I missing something? Is there a hook I'm missing?

**Comment by lafrech** [comment]
Your third sample code is fine. This is what I do [in flask-smorest](https://github.com/marshmallow-code/flask-smorest/blob/6c321d90a7898bdf0e20281cb1293f9a4dd83365/flask_smorest/spec/__init__.py).

I'm not good at type-checking but I think the type-check issue is a recurrent issue. You need either to tell the checker to ignore the check or to tell it that you know the value is not `None`, using an assert or something. In any case, this is not an issue specific to this lib IIUC.

**Comment by mwgamble** [comment]
Thanks for confirming :+1:
