### ISSUE TITLE
sdist is missing `tox.ini`

### ISSUE THREAD

**Issue by mtelka** [marshmallow-code/apispec#858]
The sdist package at PyPI is missing `tox.ini`.   Please add the missing file to sdist to make downstream testing easier.  Thank you.

**Comment by sloria** [comment]
This is addressed in https://github.com/marshmallow-code/apispec/pull/877/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R66 . So `tox.ini` will be included in the next release
