### ISSUE TITLE
How to get Schema added to components/parameters?

### ISSUE THREAD

**Issue by lukaskoeller** [marshmallow-code/apispec#890]
I have the following setup:

```py
from apispec import APISpec
from apispec.ext.marshmallow import MarshmallowPlugin
from apispec_webframeworks.flask import FlaskPlugin
```

#### Schema
```py
class FilterParams(Schema):
    month = fields.Int()
    quarter = fields.Int()
    scope_cat = fields.Str()
    scope_val = fields.Str()
    year = fields.Int()
```

#### Input
```py
"""
# …
parameters:
    - FilterParams
"""
```

#### Output
```json
"parameters": [
    {
        "$ref": "#/components/parameters/FilterParams"
    },
```

But it is actually **not** added to `components/parameters`. How can I fix this?

**Comment by lafrech** [comment]
https://apispec.readthedocs.io/en/latest/using_plugins.html#example-flask-and-marshmallow-plugins

```py
spec.components.schema("FilterParams", schema=FilterParams)
```

**Comment by lukaskoeller** [comment]
@lafrech Thanks for the quick answer. I tried that, it works, but the schema is then added to `#/components/schemas` not `#/components/parameters`

**Comment by lafrech** [comment]
You may also define parameters

https://apispec.readthedocs.io/en/latest/api_core.html#apispec.core.Components.parameter

although I'm not sure you can declare a set of parameters (not only in 
apispec, but also in OpenAPI standard).

-- 
Jérôme

**Comment by lukaskoeller** [comment]
Yeah you got a point here! I'm still quite new and didn't image that it would not be possible. Will close on that behalf. Thank you very much!

**Comment by lukaskoeller** [comment]
For anybody interested, there is an [eternally open PR](https://github.com/OAI/Overlay-Specification/issues/34) to implement parameter grouping in openapi.
