### ISSUE TITLE
`Dict()` should resolve to `{"type": "object", "additionalProperties": {}}`

### ISSUE THREAD

**Issue by luhn** [marshmallow-code/apispec#949]
`Dict` will output the schema of the `values` field as `additionalProperties`, you can see that in the example below with `Dict(values=Integer)` -> `additionalProperties: {type: integer}` and `Dict(values=Raw)` -> `additionalProperties: {}` (OpenAPI's "any" type).

To my understanding, leaving `values` to its default of `None` will allow any value input, and is effectively the same as `Dict(values=Raw())`.  So it would make more sense to output the same schema (`additionalProperties: {}`), but instead it omits `additionalProperties` entirely.  This means only an empty object complies with the spec, which is obviously not the desired behavior of `Dict()`.

```python
from apispec import APISpec

from apispec.ext.marshmallow import MarshmallowPlugin
from marshmallow import Schema, fields

spec = APISpec(
    title="Test",
    version="1.0.0",
    openapi_version="3.0.2",
    plugins=[MarshmallowPlugin()],
)


class TestSchema(Schema):
    id = fields.Int()
    plain = fields.Dict()
    raw = fields.Dict(values=fields.Raw)
    integer = fields.Dict(values=fields.Integer)


spec.components.schema("Test", schema=TestSchema)
print(spec.to_yaml())
```

Gives

```
paths: {}
info:
  title: Test
  version: 1.0.0
openapi: 3.0.2
components:
  schemas:
    Test:
      type: object
      properties:
        id:
          type: integer
        plain:
          type: object
        raw:
          type: object
          additionalProperties: {}
        integer:
          type: object
          additionalProperties:
            type: integer
```

**Comment by luhn** [comment]
Can workaround using `add_attribute_function` hook.

```python
def add_attribute_function(self, field, **kwargs):
    """
    Add `additionalProperties: {}` to Dict fields.

    """
    ret = {}
    if isinstance(field, Dict):
        if field.value_field is None:
            ret['additionalProperties'] = {}
    return ret

plugin.converter.add_attribute_function(add_attribute_function)
```

**Comment by sloria** [comment]
Interesting--I thought omitting `additionalProperties` was equivalent to `"additionalProperties": {}`. But looking at the latest spec, I don't see anything suggesting that's true. In any case, I think the behavior your suggesting is reasonable.

Thanks for reporting this!
