### ISSUE TITLE
fields2jsonschema warning about Shema Object

### ISSUE THREAD

**Issue by khorolets** [marshmallow-code/apispec#95]
Hi! Can you help me to understand the warning I'm getting.

```
... swagger.py:450: UserWarning: Only explicitly-declared fields will be included in the Schema Object. Fields defined in Meta.fields or Meta.additional are ignored.
  "Only explicitly-declared fields will be included in the Schema Object. "
```

My Schema

```python
class BaseUserSchema(ModelSchema):
    """
    Base user schema exposes only the most general fields.
    """

    class Meta:
        # pylint: disable=missing-docstring
        model = User
        fields = (
            User.id.key,
            User.username.key,
            User.first_name.key,
            User.middle_name.key,
            User.last_name.key,
        )
        dump_only = (
            User.id.key,
        )
```

And here is the sample of code where I'm getting the warning.

```python
from apispec.ext.marshmallow.swagger import schema2jsonschema
pprint(schema2jsonschema(BaseUserSchema))

... swagger.py:450: UserWarning: Only explicitly-declared fields will be included in the Schema Object. Fields defined in Meta.fields or Meta.additional are ignored.
  "Only explicitly-declared fields will be included in the Schema Object. "
{'properties': {'first_name': {'maxLength': 30, 'type': 'string'},
                'id': {'format': 'int32', 'type': 'integer'},
                'last_name': {'maxLength': 30, 'type': 'string'},
                'middle_name': {'maxLength': 30, 'type': 'string'},
                'username': {'maxLength': 80, 'type': 'string'}},
 'required': ['username'],
 'type': 'object'}
```

The result of function is as expected. But if I understand the warning right my fields declared in `Meta.fields` should be ignored.

Can you help me to understand what is this warning about?

/cc @frol

**Comment by sloria** [comment]
Ah, you can safely ignore the warning. It is meant to warn that implicitly-created fields (see https://marshmallow.readthedocs.io/en/latest/quickstart.html#refactoring-implicit-field-creation) set in `Meta.fields` will not be translated into swagger.

`ModelSchema` works a bit differently; marshmallow fields get generated based on `Meta.model` by `ModelSchema's` metaclass _upon class declaration_. Therefore, swagger fields do get generated.

We'll need to find a better condition for emitting the warning. PRs are always welcome =)

**Comment by frol** [comment]
@sloria What is the rationale behind the decision of ignoring those implicitly-created fields?

**Comment by sloria** [comment]
@frol When using `Meta.fields` with vanilla marshmallow, the fields are created implicitly upon invoking `dump` or `load`, at which point marshmallow infers which field types to use based upon the objects being dumped. Prior to invoking `dump`/`load`, apispec cannot inspect and translate those fields to swagger.

ModelSchemas infer and create fields upon class declaration, so apispec is able to translate those fields.
