### ISSUE TITLE
minLength/maxLength being added to all types

### ISSUE THREAD

**Issue by YuriHeupa** [marshmallow-code/apispec#97]
Marshmallow allows me to add validation against nested schema length, doing as the follows:

```python
class FooSchema(Schema):
    bars = fields.Nested('BarSchema', validate=Length(min=1), many=True)
```

It'll validate if the `bars` array contains at least 1 object, but using apispec to generate the spec for this schema, it'll output the follow:

```json
{
  "definitions": {
    "FooSchema": {
      "properties": {
        "bars": {
          "items": {
            "$ref": "#/definitions/BarSchema"
          },
          "minLength": 1,
          "type": "array"
        }
      }
    }
  }
}
```

Based on swagger specification http://json-schema.org/latest/json-schema-validation.html#anchor26 (5.6/5.7) the `minLength` and `maxLength` can only be used for string types, in other words these fields can't be used with arrays, so the [field2length](https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/swagger.py#L84) needs checking if the value is an array to properly add length validators.

**Comment by sloria** [comment]
The sections of the json-schema spec you linked to say 

> A string instance is valid against this keyword if its length is less than, or equal to, the value of this keyword.

But I don't see language that suggests that these keywords cannot be used for other types. Am I missing something?

**Comment by YuriHeupa** [comment]
I think that because it doesn't say it shouldn't be used not necessairly means that it could be used with other types aside from strings. I think if minlength/maxlength could be used with other types, it wouldn't fail with the existing swagger validators, however it's failing (try giving a shot with flex validator).

For array types the attrs `minItems` and `maxItems` should be used instead.

I updated my PR #98 with the appropriate changes.
